<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>FutureSubscriberTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.subscribers</a> &gt; <span class="el_source">FutureSubscriberTest.java</span></div><h1>FutureSubscriberTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.subscribers;

import static io.reactivex.internal.util.ExceptionHelper.timeoutMessage;
import static org.junit.Assert.*;

import java.util.*;
import java.util.concurrent.*;

import org.junit.*;

import io.reactivex.TestHelper;
import io.reactivex.exceptions.TestException;
import io.reactivex.internal.subscribers.FutureSubscriber;
import io.reactivex.internal.subscriptions.BooleanSubscription;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L31">public class FutureSubscriberTest {</span>

    FutureSubscriber&lt;Integer&gt; fs;

    @Before
    public void before() {
<span class="fc" id="L37">        fs = new FutureSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L38">    }</span>

    @Test
    public void cancel() throws Exception {
<span class="fc" id="L42">        assertFalse(fs.isDone());</span>

<span class="fc" id="L44">        assertFalse(fs.isCancelled());</span>

<span class="fc" id="L46">        fs.cancel();</span>

<span class="fc" id="L48">        fs.cancel();</span>

<span class="fc" id="L50">        fs.request(10);</span>

<span class="fc" id="L52">        fs.request(-99);</span>

<span class="fc" id="L54">        fs.cancel(false);</span>

<span class="fc" id="L56">        assertTrue(fs.isDone());</span>

<span class="fc" id="L58">        assertTrue(fs.isCancelled());</span>

        try {
<span class="nc" id="L61">            fs.get();</span>
<span class="nc" id="L62">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L63">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L65">        }</span>

        try {
<span class="nc" id="L68">            fs.get(1, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L69">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L70">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L72">        }</span>
<span class="fc" id="L73">    }</span>

    @Test
    public void onError() throws Exception {
<span class="fc" id="L77">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L80">            fs.onError(new TestException(&quot;One&quot;));</span>

<span class="fc" id="L82">            fs.onError(new TestException(&quot;Two&quot;));</span>

            try {
<span class="nc" id="L85">                fs.get(5, TimeUnit.MILLISECONDS);</span>
<span class="fc" id="L86">            } catch (ExecutionException ex) {</span>
<span class="fc" id="L87">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L88">                assertEquals(&quot;One&quot;, ex.getCause().getMessage());</span>
<span class="nc" id="L89">            }</span>

<span class="fc" id="L91">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Two&quot;);</span>
        } finally {
<span class="fc" id="L93">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L95">    }</span>

    @Test
    public void onNext() throws Exception {
<span class="fc" id="L99">        fs.onNext(1);</span>
<span class="fc" id="L100">        fs.onComplete();</span>

<span class="fc" id="L102">        assertEquals(1, fs.get(5, TimeUnit.MILLISECONDS).intValue());</span>
<span class="fc" id="L103">    }</span>

    @Test
    public void onSubscribe() throws Exception {
<span class="fc" id="L107">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {

<span class="fc" id="L111">            BooleanSubscription s = new BooleanSubscription();</span>

<span class="fc" id="L113">            fs.onSubscribe(s);</span>

<span class="fc" id="L115">            BooleanSubscription s2 = new BooleanSubscription();</span>

<span class="fc" id="L117">            fs.onSubscribe(s2);</span>

<span class="fc" id="L119">            assertFalse(s.isCancelled());</span>
<span class="fc" id="L120">            assertTrue(s2.isCancelled());</span>

<span class="fc" id="L122">            TestHelper.assertError(errors, 0, IllegalStateException.class, &quot;Subscription already set!&quot;);</span>
        } finally {
<span class="fc" id="L124">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L126">    }</span>

    @Test
    public void cancelRace() {
<span class="fc bfc" id="L130" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L131">            final FutureSubscriber&lt;Integer&gt; fs = new FutureSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L133">            Runnable r = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L136">                    fs.cancel(false);</span>
<span class="fc" id="L137">                }</span>
            };

<span class="fc" id="L140">            TestHelper.race(r, r);</span>
        }
<span class="fc" id="L142">    }</span>

    @Test
    public void await() throws Exception {
<span class="fc" id="L146">        Schedulers.single().scheduleDirect(new Runnable() {</span>
            @Override
            public void run() {
<span class="fc" id="L149">                fs.onNext(1);</span>
<span class="fc" id="L150">                fs.onComplete();</span>
<span class="fc" id="L151">            }</span>
        }, 100, TimeUnit.MILLISECONDS);

<span class="fc" id="L154">        assertEquals(1, fs.get(5, TimeUnit.SECONDS).intValue());</span>
<span class="fc" id="L155">    }</span>

    @Test
    public void onErrorCancelRace() {
<span class="fc bfc" id="L159" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L160">            final FutureSubscriber&lt;Integer&gt; fs = new FutureSubscriber&lt;Integer&gt;();</span>

<span class="fc" id="L162">            final TestException ex = new TestException();</span>

<span class="fc" id="L164">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L167">                    fs.cancel(false);</span>
<span class="fc" id="L168">                }</span>
            };

<span class="fc" id="L171">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L174">                    fs.onError(ex);</span>
<span class="fc" id="L175">                }</span>
            };

<span class="fc" id="L178">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L180">    }</span>

    @Test
    public void onCompleteCancelRace() {
<span class="fc bfc" id="L184" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L185">            final FutureSubscriber&lt;Integer&gt; fs = new FutureSubscriber&lt;Integer&gt;();</span>

<span class="fc bfc" id="L187" title="All 2 branches covered.">            if (i % 3 == 0) {</span>
<span class="fc" id="L188">                fs.onSubscribe(new BooleanSubscription());</span>
            }

<span class="fc bfc" id="L191" title="All 2 branches covered.">            if (i % 2 == 0) {</span>
<span class="fc" id="L192">                fs.onNext(1);</span>
            }

<span class="fc" id="L195">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L198">                    fs.cancel(false);</span>
<span class="fc" id="L199">                }</span>
            };

<span class="fc" id="L202">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L205">                    fs.onComplete();</span>
<span class="fc" id="L206">                }</span>
            };

<span class="fc" id="L209">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L211">    }</span>

    @Test
    public void onErrorOnComplete() throws Exception {
<span class="fc" id="L215">        fs.onError(new TestException(&quot;One&quot;));</span>
<span class="fc" id="L216">        fs.onComplete();</span>

        try {
<span class="nc" id="L219">            fs.get(5, TimeUnit.MILLISECONDS);</span>
<span class="fc" id="L220">        } catch (ExecutionException ex) {</span>
<span class="fc" id="L221">            assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L222">            assertEquals(&quot;One&quot;, ex.getCause().getMessage());</span>
<span class="nc" id="L223">        }</span>
<span class="fc" id="L224">    }</span>

    @Test
    public void onCompleteOnError() throws Exception {
<span class="fc" id="L228">        fs.onComplete();</span>
<span class="fc" id="L229">        fs.onError(new TestException(&quot;One&quot;));</span>

        try {
<span class="nc" id="L232">            assertNull(fs.get(5, TimeUnit.MILLISECONDS));</span>
<span class="fc" id="L233">        } catch (ExecutionException ex) {</span>
<span class="fc" id="L234">            assertTrue(ex.toString(), ex.getCause() instanceof NoSuchElementException);</span>
<span class="nc" id="L235">        }</span>
<span class="fc" id="L236">    }</span>

    @Test
    public void cancelOnError() throws Exception {
<span class="fc" id="L240">        fs.cancel(true);</span>
<span class="fc" id="L241">        fs.onError(new TestException(&quot;One&quot;));</span>

        try {
<span class="nc" id="L244">            fs.get(5, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L245">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L246">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L248">        }</span>
<span class="fc" id="L249">    }</span>

    @Test
    public void cancelOnComplete() throws Exception {
<span class="fc" id="L253">        fs.cancel(true);</span>
<span class="fc" id="L254">        fs.onComplete();</span>

        try {
<span class="nc" id="L257">            fs.get(5, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L258">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L259">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L261">        }</span>
<span class="fc" id="L262">    }</span>

    @Test
    public void onNextThenOnCompleteTwice() throws Exception {
<span class="fc" id="L266">        fs.onNext(1);</span>
<span class="fc" id="L267">        fs.onComplete();</span>
<span class="fc" id="L268">        fs.onComplete();</span>

<span class="fc" id="L270">        assertEquals(1, fs.get(5, TimeUnit.MILLISECONDS).intValue());</span>
<span class="fc" id="L271">    }</span>

    @Test
    public void completeAsync() throws Exception {
<span class="fc" id="L275">        Schedulers.single().scheduleDirect(new Runnable() {</span>
            @Override
            public void run() {
<span class="fc" id="L278">                fs.onNext(1);</span>
<span class="fc" id="L279">                fs.onComplete();</span>
<span class="fc" id="L280">            }</span>
        }, 500, TimeUnit.MILLISECONDS);

<span class="fc" id="L283">        assertEquals(1, fs.get().intValue());</span>
<span class="fc" id="L284">    }</span>

    @Test
    public void getTimedOut() throws Exception {
        try {
<span class="nc" id="L289">            fs.get(1, TimeUnit.NANOSECONDS);</span>
<span class="nc" id="L290">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L291">        } catch (TimeoutException expected) {</span>
<span class="fc" id="L292">            assertEquals(timeoutMessage(1, TimeUnit.NANOSECONDS), expected.getMessage());</span>
<span class="nc" id="L293">        }</span>
<span class="fc" id="L294">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>