<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableConcatMapCompletableTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableConcatMapCompletableTest.java</span></div><h1>ObservableConcatMapCompletableTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 * &lt;p&gt;
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * &lt;p&gt;
 * http://www.apache.org/licenses/LICENSE-2.0
 * &lt;p&gt;
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */
package io.reactivex.internal.operators.observable;

import static org.junit.Assert.assertTrue;

import java.util.List;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Function;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.*;

<span class="fc" id="L29">public class ObservableConcatMapCompletableTest {</span>

    @Test
    public void asyncFused() throws Exception {
<span class="fc" id="L33">        UnicastSubject&lt;Integer&gt; us = UnicastSubject.create();</span>

<span class="fc" id="L35">        TestObserver&lt;Void&gt; to = us.concatMapCompletable(completableComplete(), 2).test();</span>

<span class="fc" id="L37">        us.onNext(1);</span>
<span class="fc" id="L38">        us.onComplete();</span>

<span class="fc" id="L40">        to.assertComplete();</span>
<span class="fc" id="L41">        to.assertValueCount(0);</span>
<span class="fc" id="L42">    }</span>

    @Test
    public void notFused() throws Exception {
<span class="fc" id="L46">        UnicastSubject&lt;Integer&gt; us = UnicastSubject.create();</span>
<span class="fc" id="L47">        TestObserver&lt;Void&gt; to = us.hide().concatMapCompletable(completableComplete(), 2).test();</span>

<span class="fc" id="L49">        us.onNext(1);</span>
<span class="fc" id="L50">        us.onNext(2);</span>
<span class="fc" id="L51">        us.onComplete();</span>

<span class="fc" id="L53">        to.assertComplete();</span>
<span class="fc" id="L54">        to.assertValueCount(0);</span>
<span class="fc" id="L55">        to.assertNoErrors();</span>
<span class="fc" id="L56">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L60">        TestHelper.checkDisposed(Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L61">        .concatMapCompletable(completableError()));</span>
<span class="fc" id="L62">    }</span>

    @Test
    public void mainError() {
<span class="fc" id="L66">        Observable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L67">        .concatMapCompletable(completableComplete())</span>
<span class="fc" id="L68">        .test()</span>
<span class="fc" id="L69">        .assertFailure(TestException.class);</span>
<span class="fc" id="L70">    }</span>

    @Test
    public void innerError() {
<span class="fc" id="L74">        Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L75">        .concatMapCompletable(completableError())</span>
<span class="fc" id="L76">        .test()</span>
<span class="fc" id="L77">        .assertFailure(TestException.class);</span>
<span class="fc" id="L78">    }</span>

    @Test
    public void badSource() {
<span class="fc" id="L82">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L84">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L87">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L89">                    observer.onNext(1);</span>
<span class="fc" id="L90">                    observer.onComplete();</span>
<span class="fc" id="L91">                    observer.onNext(2);</span>
<span class="fc" id="L92">                    observer.onError(new TestException());</span>
<span class="fc" id="L93">                    observer.onComplete();</span>
<span class="fc" id="L94">                }</span>
            }
<span class="fc" id="L96">            .concatMapCompletable(completableComplete())</span>
<span class="fc" id="L97">            .test()</span>
<span class="fc" id="L98">            .assertComplete();</span>

<span class="fc" id="L100">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L102">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L104">    }</span>

    @Test
    public void onErrorRace() {
<span class="fc bfc" id="L108" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L109">            List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
            try {
<span class="fc" id="L111">                final PublishSubject&lt;Integer&gt; ps1 = PublishSubject.create();</span>
<span class="fc" id="L112">                final PublishSubject&lt;Integer&gt; ps2 = PublishSubject.create();</span>

<span class="fc" id="L114">                TestObserver&lt;Void&gt; to = ps1.concatMapCompletable(new Function&lt;Integer, CompletableSource&gt;() {</span>
                    @Override
                    public CompletableSource apply(Integer v) throws Exception {
<span class="nc" id="L117">                        return Completable.fromObservable(ps2);</span>
                    }
<span class="fc" id="L119">                }).test();</span>

<span class="fc" id="L121">                final TestException ex1 = new TestException();</span>
<span class="fc" id="L122">                final TestException ex2 = new TestException();</span>

<span class="fc" id="L124">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L127">                        ps1.onError(ex1);</span>
<span class="fc" id="L128">                    }</span>
                };
<span class="fc" id="L130">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L133">                        ps2.onError(ex2);</span>
<span class="fc" id="L134">                    }</span>
                };

<span class="fc" id="L137">                TestHelper.race(r1, r2);</span>

<span class="fc" id="L139">                to.assertFailure(TestException.class);</span>

<span class="pc bpc" id="L141" title="1 of 2 branches missed.">                if (!errors.isEmpty()) {</span>
<span class="nc" id="L142">                    TestHelper.assertError(errors, 0, TestException.class);</span>
                }
            } finally {
<span class="fc" id="L145">                RxJavaPlugins.reset();</span>
            }
        }
<span class="fc" id="L148">    }</span>

    @Test
    public void mapperThrows() {
<span class="fc" id="L152">        Observable.just(1).hide()</span>
<span class="fc" id="L153">        .concatMapCompletable(completableThrows())</span>
<span class="fc" id="L154">        .test()</span>
<span class="fc" id="L155">        .assertFailure(TestException.class);</span>
<span class="fc" id="L156">    }</span>

    @Test
    public void fusedPollThrows() {
<span class="fc" id="L160">        Observable.just(1)</span>
<span class="fc" id="L161">        .map(new Function&lt;Integer, Integer&gt;() {</span>
            @Override
            public Integer apply(Integer v) throws Exception {
<span class="fc" id="L164">                throw new TestException();</span>
            }
        })
<span class="fc" id="L167">        .concatMapCompletable(completableComplete())</span>
<span class="fc" id="L168">        .test()</span>
<span class="fc" id="L169">        .assertFailure(TestException.class);</span>
<span class="fc" id="L170">    }</span>

    @Test
    public void concatReportsDisposedOnComplete() {
<span class="fc" id="L174">        final Disposable[] disposable = { null };</span>

<span class="fc" id="L176">        Observable.just(1)</span>
<span class="fc" id="L177">        .hide()</span>
<span class="fc" id="L178">        .concatMapCompletable(completableComplete())</span>
<span class="fc" id="L179">        .subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {
<span class="fc" id="L183">                disposable[0] = d;</span>
<span class="fc" id="L184">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L188">            }</span>

            @Override
            public void onComplete() {
<span class="fc" id="L192">            }</span>
        });

<span class="fc" id="L195">        assertTrue(disposable[0].isDisposed());</span>
<span class="fc" id="L196">    }</span>

    @Test
    public void concatReportsDisposedOnError() {
<span class="fc" id="L200">        final Disposable[] disposable = { null };</span>

<span class="fc" id="L202">        Observable.just(1)</span>
<span class="fc" id="L203">        .hide()</span>
<span class="fc" id="L204">        .concatMapCompletable(completableError())</span>
<span class="fc" id="L205">        .subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {
<span class="fc" id="L209">                disposable[0] = d;</span>
<span class="fc" id="L210">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L214">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L218">            }</span>
        });

<span class="fc" id="L221">        assertTrue(disposable[0].isDisposed());</span>
<span class="fc" id="L222">    }</span>

    private Function&lt;Integer, CompletableSource&gt; completableComplete() {
<span class="fc" id="L225">        return new Function&lt;Integer, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Integer v) throws Exception {
<span class="fc" id="L228">                return Completable.complete();</span>
            }
        };
    }

    private Function&lt;Integer, CompletableSource&gt; completableError() {
<span class="fc" id="L234">        return new Function&lt;Integer, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Integer v) throws Exception {
<span class="fc" id="L237">                return Completable.error(new TestException());</span>
            }
        };
    }

    private Function&lt;Integer, CompletableSource&gt; completableThrows() {
<span class="fc" id="L243">        return new Function&lt;Integer, CompletableSource&gt;() {</span>
            @Override
            public CompletableSource apply(Integer v) throws Exception {
<span class="fc" id="L246">                throw new TestException();</span>
            }
        };
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>