<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableConcatMapTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableConcatMapTest.java</span></div><h1>ObservableConcatMapTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.*;

import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.*;

<span class="fc" id="L33">public class ObservableConcatMapTest {</span>

    @Test
    public void asyncFused() {
<span class="fc" id="L37">        UnicastSubject&lt;Integer&gt; us = UnicastSubject.create();</span>

<span class="fc" id="L39">        TestObserver&lt;Integer&gt; to = us.concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L42">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L45">        .test();</span>

<span class="fc" id="L47">        us.onNext(1);</span>
<span class="fc" id="L48">        us.onComplete();</span>

<span class="fc" id="L50">        to.assertResult(1, 2);</span>
<span class="fc" id="L51">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L55">        TestHelper.checkDisposed(Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L56">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L59">                return Observable.error(new TestException());</span>
            }
        }));
<span class="fc" id="L62">    }</span>

    @Test
    public void dispose2() {
<span class="fc" id="L66">        TestHelper.checkDisposed(Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L67">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L70">                return Observable.error(new TestException());</span>
            }
        }));
<span class="fc" id="L73">    }</span>

    @Test
    public void mainError() {
<span class="fc" id="L77">        Observable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L78">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L81">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L84">        .test()</span>
<span class="fc" id="L85">        .assertFailure(TestException.class);</span>
<span class="fc" id="L86">    }</span>

    @Test
    public void innerError() {
<span class="fc" id="L90">        Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L91">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L94">                return Observable.error(new TestException());</span>
            }
        })
<span class="fc" id="L97">        .test()</span>
<span class="fc" id="L98">        .assertFailure(TestException.class);</span>
<span class="fc" id="L99">    }</span>

    @Test
    public void mainErrorDelayed() {
<span class="fc" id="L103">        Observable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L104">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L107">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L110">        .test()</span>
<span class="fc" id="L111">        .assertFailure(TestException.class);</span>
<span class="fc" id="L112">    }</span>

    @Test
    public void innerErrorDelayError() {
<span class="fc" id="L116">        Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L117">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L120">                return Observable.error(new TestException());</span>
            }
        })
<span class="fc" id="L123">        .test()</span>
<span class="fc" id="L124">        .assertFailure(TestException.class);</span>
<span class="fc" id="L125">    }</span>

    @Test
    public void innerErrorDelayError2() {
<span class="fc" id="L129">        Observable.&lt;Integer&gt;just(1).hide()</span>
<span class="fc" id="L130">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L133">                return Observable.fromCallable(new Callable&lt;Integer&gt;() {</span>
                    @Override
                    public Integer call() throws Exception {
<span class="fc" id="L136">                        throw new TestException();</span>
                    }
                });
            }
        })
<span class="fc" id="L141">        .test()</span>
<span class="fc" id="L142">        .assertFailure(TestException.class);</span>
<span class="fc" id="L143">    }</span>

    @Test
    public void badSource() {
<span class="fc" id="L147">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L149">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L152">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L154">                    observer.onNext(1);</span>
<span class="fc" id="L155">                    observer.onComplete();</span>
<span class="fc" id="L156">                    observer.onNext(2);</span>
<span class="fc" id="L157">                    observer.onError(new TestException());</span>
<span class="fc" id="L158">                    observer.onComplete();</span>
<span class="fc" id="L159">                }</span>
            }
<span class="fc" id="L161">            .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L164">                    return Observable.range(v, 2);</span>
                }
            })
<span class="fc" id="L167">            .test()</span>
<span class="fc" id="L168">            .assertResult(1, 2);</span>

<span class="fc" id="L170">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L172">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L174">    }</span>

    @Test
    public void badSourceDelayError() {
<span class="fc" id="L178">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L180">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L183">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L185">                    observer.onNext(1);</span>
<span class="fc" id="L186">                    observer.onComplete();</span>
<span class="fc" id="L187">                    observer.onNext(2);</span>
<span class="fc" id="L188">                    observer.onError(new TestException());</span>
<span class="fc" id="L189">                    observer.onComplete();</span>
<span class="fc" id="L190">                }</span>
            }
<span class="fc" id="L192">            .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L195">                    return Observable.range(v, 2);</span>
                }
            })
<span class="fc" id="L198">            .test()</span>
<span class="fc" id="L199">            .assertResult(1, 2);</span>

<span class="fc" id="L201">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L203">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L205">    }</span>

    @Test
    public void normalDelayErrors() {
<span class="fc" id="L209">        Observable.just(1).hide()</span>
<span class="fc" id="L210">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L213">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L216">        .test()</span>
<span class="fc" id="L217">        .assertResult(1, 2);</span>
<span class="fc" id="L218">    }</span>

    @Test
    public void normalDelayErrorsTillTheEnd() {
<span class="fc" id="L222">        Observable.just(1).hide()</span>
<span class="fc" id="L223">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L226">                return Observable.range(v, 2);</span>
            }
        }, 16, true)
<span class="fc" id="L229">        .test()</span>
<span class="fc" id="L230">        .assertResult(1, 2);</span>
<span class="fc" id="L231">    }</span>

    @Test
    public void onErrorRace() {
<span class="fc bfc" id="L235" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L236">            List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
            try {
<span class="fc" id="L238">                final PublishSubject&lt;Integer&gt; ps1 = PublishSubject.create();</span>
<span class="fc" id="L239">                final PublishSubject&lt;Integer&gt; ps2 = PublishSubject.create();</span>

<span class="fc" id="L241">                TestObserver&lt;Integer&gt; to = ps1.concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
                    @Override
                    public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L244">                        return ps2;</span>
                    }
<span class="fc" id="L246">                }).test();</span>

<span class="fc" id="L248">                final TestException ex1 = new TestException();</span>
<span class="fc" id="L249">                final TestException ex2 = new TestException();</span>

<span class="fc" id="L251">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L254">                        ps1.onError(ex1);</span>
<span class="fc" id="L255">                    }</span>
                };
<span class="fc" id="L257">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L260">                        ps2.onError(ex2);</span>
<span class="fc" id="L261">                    }</span>
                };

<span class="fc" id="L264">                TestHelper.race(r1, r2);</span>

<span class="fc" id="L266">                to.assertFailure(TestException.class);</span>

<span class="pc bpc" id="L268" title="1 of 2 branches missed.">                if (!errors.isEmpty()) {</span>
<span class="nc" id="L269">                    TestHelper.assertError(errors, 0, TestException.class);</span>
                }
            } finally {
<span class="fc" id="L272">                RxJavaPlugins.reset();</span>
            }
        }
<span class="fc" id="L275">    }</span>

    @Test
    public void mapperThrows() {
<span class="fc" id="L279">        Observable.just(1).hide()</span>
<span class="fc" id="L280">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L283">                throw new TestException();</span>
            }
        })
<span class="fc" id="L286">        .test()</span>
<span class="fc" id="L287">        .assertFailure(TestException.class);</span>
<span class="fc" id="L288">    }</span>

    @Test
    public void fusedPollThrows() {
<span class="fc" id="L292">        Observable.just(1)</span>
<span class="fc" id="L293">        .map(new Function&lt;Integer, Integer&gt;() {</span>
            @Override
            public Integer apply(Integer v) throws Exception {
<span class="fc" id="L296">                throw new TestException();</span>
            }
        })
<span class="fc" id="L299">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L302">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L305">        .test()</span>
<span class="fc" id="L306">        .assertFailure(TestException.class);</span>
<span class="fc" id="L307">    }</span>

    @Test
    public void fusedPollThrowsDelayError() {
<span class="fc" id="L311">        Observable.just(1)</span>
<span class="fc" id="L312">        .map(new Function&lt;Integer, Integer&gt;() {</span>
            @Override
            public Integer apply(Integer v) throws Exception {
<span class="fc" id="L315">                throw new TestException();</span>
            }
        })
<span class="fc" id="L318">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="nc" id="L321">                return Observable.range(v, 2);</span>
            }
        })
<span class="fc" id="L324">        .test()</span>
<span class="fc" id="L325">        .assertFailure(TestException.class);</span>
<span class="fc" id="L326">    }</span>

    @Test
    public void mapperThrowsDelayError() {
<span class="fc" id="L330">        Observable.just(1).hide()</span>
<span class="fc" id="L331">        .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L334">                throw new TestException();</span>
            }
        })
<span class="fc" id="L337">        .test()</span>
<span class="fc" id="L338">        .assertFailure(TestException.class);</span>
<span class="fc" id="L339">    }</span>

    @Test
    public void badInnerDelayError() {
        @SuppressWarnings(&quot;rawtypes&quot;)
<span class="fc" id="L344">        final Observer[] o = { null };</span>

<span class="fc" id="L346">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L349">            Observable.just(1).hide()</span>
<span class="fc" id="L350">            .concatMapDelayError(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L353">                    return new Observable&lt;Integer&gt;() {</span>
                        @Override
                        protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L356">                            o[0] = observer;</span>
<span class="fc" id="L357">                            observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L358">                            observer.onComplete();</span>
<span class="fc" id="L359">                        }</span>
                    };
                }
            })
<span class="fc" id="L363">            .test()</span>
<span class="fc" id="L364">            .assertResult();</span>

<span class="fc" id="L366">            o[0].onError(new TestException());</span>

<span class="fc" id="L368">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L370">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L372">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void concatReportsDisposedOnComplete() {
<span class="fc" id="L377">        final Disposable[] disposable = { null };</span>

<span class="fc" id="L379">        Observable.fromArray(Observable.just(1), Observable.just(2))</span>
<span class="fc" id="L380">        .hide()</span>
<span class="fc" id="L381">        .concatMap(Functions.&lt;Observable&lt;Integer&gt;&gt;identity())</span>
<span class="fc" id="L382">        .subscribe(new Observer&lt;Integer&gt;() {</span>

            @Override
            public void onSubscribe(Disposable d) {
<span class="fc" id="L386">                disposable[0] = d;</span>
<span class="fc" id="L387">            }</span>

            @Override
            public void onNext(Integer t) {
<span class="fc" id="L391">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L395">            }</span>

            @Override
            public void onComplete() {
<span class="fc" id="L399">            }</span>
        });

<span class="fc" id="L402">        assertTrue(disposable[0].isDisposed());</span>
<span class="fc" id="L403">    }</span>

    @Test
    @SuppressWarnings(&quot;unchecked&quot;)
    public void concatReportsDisposedOnError() {
<span class="fc" id="L408">        final Disposable[] disposable = { null };</span>

<span class="fc" id="L410">        Observable.fromArray(Observable.just(1), Observable.&lt;Integer&gt;error(new TestException()))</span>
<span class="fc" id="L411">        .hide()</span>
<span class="fc" id="L412">        .concatMap(Functions.&lt;Observable&lt;Integer&gt;&gt;identity())</span>
<span class="fc" id="L413">        .subscribe(new Observer&lt;Integer&gt;() {</span>

            @Override
            public void onSubscribe(Disposable d) {
<span class="fc" id="L417">                disposable[0] = d;</span>
<span class="fc" id="L418">            }</span>

            @Override
            public void onNext(Integer t) {
<span class="fc" id="L422">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L426">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L430">            }</span>
        });

<span class="fc" id="L433">        assertTrue(disposable[0].isDisposed());</span>
<span class="fc" id="L434">    }</span>

    @Test
    public void reentrantNoOverflow() {
<span class="fc" id="L438">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L440">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L442">            TestObserver&lt;Integer&gt; to = ps.concatMap(new Function&lt;Integer, Observable&lt;Integer&gt;&gt;() {</span>
                @Override
                public Observable&lt;Integer&gt; apply(Integer v)
                        throws Exception {
<span class="fc" id="L446">                    return Observable.just(v + 1);</span>
                }
            }, 1)
<span class="fc" id="L449">            .subscribeWith(new TestObserver&lt;Integer&gt;() {</span>
                @Override
                public void onNext(Integer t) {
<span class="fc" id="L452">                    super.onNext(t);</span>
<span class="fc bfc" id="L453" title="All 2 branches covered.">                    if (t == 1) {</span>
<span class="fc bfc" id="L454" title="All 2 branches covered.">                        for (int i = 1; i &lt; 10; i++) {</span>
<span class="fc" id="L455">                            ps.onNext(i);</span>
                        }
<span class="fc" id="L457">                        ps.onComplete();</span>
                    }
<span class="fc" id="L459">                }</span>
            });

<span class="fc" id="L462">            ps.onNext(0);</span>

<span class="pc bpc" id="L464" title="1 of 2 branches missed.">            if (!errors.isEmpty()) {</span>
<span class="nc" id="L465">                to.onError(new CompositeException(errors));</span>
            }

<span class="fc" id="L468">            to.assertResult(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);</span>
        } finally {
<span class="fc" id="L470">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L472">    }</span>

    @Test
    public void reentrantNoOverflowHidden() {
<span class="fc" id="L476">        final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L478">        TestObserver&lt;Integer&gt; to = ps.concatMap(new Function&lt;Integer, Observable&lt;Integer&gt;&gt;() {</span>
            @Override
            public Observable&lt;Integer&gt; apply(Integer v)
                    throws Exception {
<span class="fc" id="L482">                return Observable.just(v + 1).hide();</span>
            }
        }, 1)
<span class="fc" id="L485">        .subscribeWith(new TestObserver&lt;Integer&gt;() {</span>
            @Override
            public void onNext(Integer t) {
<span class="fc" id="L488">                super.onNext(t);</span>
<span class="fc bfc" id="L489" title="All 2 branches covered.">                if (t == 1) {</span>
<span class="fc bfc" id="L490" title="All 2 branches covered.">                    for (int i = 1; i &lt; 10; i++) {</span>
<span class="fc" id="L491">                        ps.onNext(i);</span>
                    }
<span class="fc" id="L493">                    ps.onComplete();</span>
                }
<span class="fc" id="L495">            }</span>
        });

<span class="fc" id="L498">        ps.onNext(0);</span>

<span class="fc" id="L500">        to.assertResult(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);</span>
<span class="fc" id="L501">    }</span>

    @Test
    public void noCancelPrevious() {
<span class="fc" id="L505">        final AtomicInteger counter = new AtomicInteger();</span>

<span class="fc" id="L507">        Observable.range(1, 5)</span>
<span class="fc" id="L508">        .concatMap(new Function&lt;Integer, ObservableSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Integer&gt; apply(Integer v) throws Exception {
<span class="fc" id="L511">                return Observable.just(v).doOnDispose(new Action() {</span>
                    @Override
                    public void run() throws Exception {
<span class="nc" id="L514">                        counter.getAndIncrement();</span>
<span class="nc" id="L515">                    }</span>
                });
            }
        })
<span class="fc" id="L519">        .test()</span>
<span class="fc" id="L520">        .assertResult(1, 2, 3, 4, 5);</span>

<span class="fc" id="L522">        assertEquals(0, counter.get());</span>
<span class="fc" id="L523">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>