<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableElementAtTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableElementAtTest.java</span></div><h1>ObservableElementAtTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.*;

import java.util.*;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.disposables.Disposables;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Function;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L31">public class ObservableElementAtTest {</span>

    @Test
    public void testElementAtObservable() {
<span class="fc" id="L35">        assertEquals(2, Observable.fromArray(1, 2).elementAt(1).toObservable().blockingSingle()</span>
<span class="fc" id="L36">                .intValue());</span>
<span class="fc" id="L37">    }</span>

    @Test
    public void testElementAtWithIndexOutOfBoundsObservable() {
<span class="fc" id="L41">        assertEquals(-99, Observable.fromArray(1, 2).elementAt(2).toObservable().blockingSingle(-99).intValue());</span>
<span class="fc" id="L42">    }</span>

    @Test
    public void testElementAtOrDefaultObservable() {
<span class="fc" id="L46">        assertEquals(2, Observable.fromArray(1, 2).elementAt(1, 0).toObservable().blockingSingle().intValue());</span>
<span class="fc" id="L47">    }</span>

    @Test
    public void testElementAtOrDefaultWithIndexOutOfBoundsObservable() {
<span class="fc" id="L51">        assertEquals(0, Observable.fromArray(1, 2).elementAt(2, 0).toObservable().blockingSingle().intValue());</span>
<span class="fc" id="L52">    }</span>

    @Test
    public void testElementAt() {
<span class="fc" id="L56">        assertEquals(2, Observable.fromArray(1, 2).elementAt(1).blockingGet()</span>
<span class="fc" id="L57">                .intValue());</span>
<span class="fc" id="L58">    }</span>

    @Test(expected = IndexOutOfBoundsException.class)
    public void testElementAtWithMinusIndex() {
<span class="nc" id="L62">        Observable.fromArray(1, 2).elementAt(-1);</span>
<span class="nc" id="L63">    }</span>

    @Test
    public void testElementAtWithIndexOutOfBounds() {
<span class="fc" id="L67">        assertNull(Observable.fromArray(1, 2).elementAt(2).blockingGet());</span>
<span class="fc" id="L68">    }</span>

    @Test
    public void testElementAtOrDefault() {
<span class="fc" id="L72">        assertEquals(2, Observable.fromArray(1, 2).elementAt(1, 0).blockingGet().intValue());</span>
<span class="fc" id="L73">    }</span>

    @Test
    public void testElementAtOrDefaultWithIndexOutOfBounds() {
<span class="fc" id="L77">        assertEquals(0, Observable.fromArray(1, 2).elementAt(2, 0).blockingGet().intValue());</span>
<span class="fc" id="L78">    }</span>

    @Test(expected = IndexOutOfBoundsException.class)
    public void testElementAtOrDefaultWithMinusIndex() {
<span class="nc" id="L82">        Observable.fromArray(1, 2).elementAt(-1, 0);</span>
<span class="nc" id="L83">    }</span>

    @Test(expected = IndexOutOfBoundsException.class)
    public void elementAtOrErrorNegativeIndex() {
<span class="fc" id="L87">        Observable.empty()</span>
<span class="nc" id="L88">            .elementAtOrError(-1);</span>
<span class="nc" id="L89">    }</span>

    @Test
    public void elementAtOrErrorNoElement() {
<span class="fc" id="L93">        Observable.empty()</span>
<span class="fc" id="L94">            .elementAtOrError(0)</span>
<span class="fc" id="L95">            .test()</span>
<span class="fc" id="L96">            .assertNoValues()</span>
<span class="fc" id="L97">            .assertError(NoSuchElementException.class);</span>
<span class="fc" id="L98">    }</span>

    @Test
    public void elementAtOrErrorOneElement() {
<span class="fc" id="L102">        Observable.just(1)</span>
<span class="fc" id="L103">            .elementAtOrError(0)</span>
<span class="fc" id="L104">            .test()</span>
<span class="fc" id="L105">            .assertNoErrors()</span>
<span class="fc" id="L106">            .assertValue(1);</span>
<span class="fc" id="L107">    }</span>

    @Test
    public void elementAtOrErrorMultipleElements() {
<span class="fc" id="L111">        Observable.just(1, 2, 3)</span>
<span class="fc" id="L112">            .elementAtOrError(1)</span>
<span class="fc" id="L113">            .test()</span>
<span class="fc" id="L114">            .assertNoErrors()</span>
<span class="fc" id="L115">            .assertValue(2);</span>
<span class="fc" id="L116">    }</span>

    @Test
    public void elementAtOrErrorInvalidIndex() {
<span class="fc" id="L120">        Observable.just(1, 2, 3)</span>
<span class="fc" id="L121">            .elementAtOrError(3)</span>
<span class="fc" id="L122">            .test()</span>
<span class="fc" id="L123">            .assertNoValues()</span>
<span class="fc" id="L124">            .assertError(NoSuchElementException.class);</span>
<span class="fc" id="L125">    }</span>

    @Test
    public void elementAtOrErrorError() {
<span class="fc" id="L129">        Observable.error(new RuntimeException(&quot;error&quot;))</span>
<span class="fc" id="L130">            .elementAtOrError(0)</span>
<span class="fc" id="L131">            .test()</span>
<span class="fc" id="L132">            .assertNoValues()</span>
<span class="fc" id="L133">            .assertErrorMessage(&quot;error&quot;)</span>
<span class="fc" id="L134">            .assertError(RuntimeException.class);</span>
<span class="fc" id="L135">    }</span>

    @Test
    public void elementAtIndex0OnEmptySource() {
<span class="fc" id="L139">        Observable.empty()</span>
<span class="fc" id="L140">            .elementAt(0)</span>
<span class="fc" id="L141">            .test()</span>
<span class="fc" id="L142">            .assertResult();</span>
<span class="fc" id="L143">    }</span>

    @Test
    public void elementAtIndex0WithDefaultOnEmptySource() {
<span class="fc" id="L147">        Observable.empty()</span>
<span class="fc" id="L148">            .elementAt(0, 5)</span>
<span class="fc" id="L149">            .test()</span>
<span class="fc" id="L150">            .assertResult(5);</span>
<span class="fc" id="L151">    }</span>

    @Test
    public void elementAtIndex1OnEmptySource() {
<span class="fc" id="L155">        Observable.empty()</span>
<span class="fc" id="L156">            .elementAt(1)</span>
<span class="fc" id="L157">            .test()</span>
<span class="fc" id="L158">            .assertResult();</span>
<span class="fc" id="L159">    }</span>

    @Test
    public void elementAtIndex1WithDefaultOnEmptySource() {
<span class="fc" id="L163">        Observable.empty()</span>
<span class="fc" id="L164">            .elementAt(1, 10)</span>
<span class="fc" id="L165">            .test()</span>
<span class="fc" id="L166">            .assertResult(10);</span>
<span class="fc" id="L167">    }</span>

    @Test
    public void elementAtOrErrorIndex1OnEmptySource() {
<span class="fc" id="L171">        Observable.empty()</span>
<span class="fc" id="L172">            .elementAtOrError(1)</span>
<span class="fc" id="L173">            .test()</span>
<span class="fc" id="L174">            .assertFailure(NoSuchElementException.class);</span>
<span class="fc" id="L175">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L179">        TestHelper.checkDisposed(PublishSubject.create().elementAt(0).toObservable());</span>
<span class="fc" id="L180">        TestHelper.checkDisposed(PublishSubject.create().elementAt(0));</span>

<span class="fc" id="L182">        TestHelper.checkDisposed(PublishSubject.create().elementAt(0, 1).toObservable());</span>
<span class="fc" id="L183">        TestHelper.checkDisposed(PublishSubject.create().elementAt(0, 1));</span>
<span class="fc" id="L184">    }</span>

    @Test
    public void doubleOnSubscribe() {
<span class="fc" id="L188">        TestHelper.checkDoubleOnSubscribeObservable(new Function&lt;Observable&lt;Object&gt;, ObservableSource&lt;Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;Object&gt; apply(Observable&lt;Object&gt; o) throws Exception {
<span class="fc" id="L191">                return o.elementAt(0).toObservable();</span>
            }
        });

<span class="fc" id="L195">        TestHelper.checkDoubleOnSubscribeObservableToMaybe(new Function&lt;Observable&lt;Object&gt;, MaybeSource&lt;Object&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Object&gt; apply(Observable&lt;Object&gt; o) throws Exception {
<span class="fc" id="L198">                return o.elementAt(0);</span>
            }
        });

<span class="fc" id="L202">        TestHelper.checkDoubleOnSubscribeObservableToSingle(new Function&lt;Observable&lt;Object&gt;, SingleSource&lt;Object&gt;&gt;() {</span>
            @Override
            public SingleSource&lt;Object&gt; apply(Observable&lt;Object&gt; o) throws Exception {
<span class="fc" id="L205">                return o.elementAt(0, 1);</span>
            }
        });
<span class="fc" id="L208">    }</span>

    @Test
    public void elementAtIndex1WithDefaultOnEmptySourceObservable() {
<span class="fc" id="L212">        Observable.empty()</span>
<span class="fc" id="L213">            .elementAt(1, 10)</span>
<span class="fc" id="L214">            .toObservable()</span>
<span class="fc" id="L215">            .test()</span>
<span class="fc" id="L216">            .assertResult(10);</span>
<span class="fc" id="L217">    }</span>

    @Test
    public void errorObservable() {
<span class="fc" id="L221">        Observable.error(new TestException())</span>
<span class="fc" id="L222">            .elementAt(1, 10)</span>
<span class="fc" id="L223">            .toObservable()</span>
<span class="fc" id="L224">            .test()</span>
<span class="fc" id="L225">            .assertFailure(TestException.class);</span>
<span class="fc" id="L226">    }</span>

    @Test
    public void badSourceObservable() {
<span class="fc" id="L230">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L232">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L235">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L237">                    observer.onNext(1);</span>
<span class="fc" id="L238">                    observer.onNext(2);</span>
<span class="fc" id="L239">                    observer.onError(new TestException());</span>
<span class="fc" id="L240">                    observer.onComplete();</span>
<span class="fc" id="L241">                }</span>
            }
<span class="fc" id="L243">            .elementAt(0)</span>
<span class="fc" id="L244">            .toObservable()</span>
<span class="fc" id="L245">            .test()</span>
<span class="fc" id="L246">            .assertResult(1);</span>

<span class="fc" id="L248">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L250">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L252">    }</span>

    @Test
    public void badSource() {
<span class="fc" id="L256">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L258">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L261">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L263">                    observer.onNext(1);</span>
<span class="fc" id="L264">                    observer.onNext(2);</span>
<span class="fc" id="L265">                    observer.onError(new TestException());</span>
<span class="fc" id="L266">                    observer.onComplete();</span>
<span class="fc" id="L267">                }</span>
            }
<span class="fc" id="L269">            .elementAt(0)</span>
<span class="fc" id="L270">            .test()</span>
<span class="fc" id="L271">            .assertResult(1);</span>

<span class="fc" id="L273">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L275">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L277">    }</span>

    @Test
    public void badSource2() {
<span class="fc" id="L281">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L283">            new Observable&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L286">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L288">                    observer.onNext(1);</span>
<span class="fc" id="L289">                    observer.onNext(2);</span>
<span class="fc" id="L290">                    observer.onError(new TestException());</span>
<span class="fc" id="L291">                    observer.onComplete();</span>
<span class="fc" id="L292">                }</span>
            }
<span class="fc" id="L294">            .elementAt(0, 1)</span>
<span class="fc" id="L295">            .test()</span>
<span class="fc" id="L296">            .assertResult(1);</span>

<span class="fc" id="L298">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L300">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L302">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>