<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableFromCallableTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableFromCallableTest.java</span></div><h1>ObservableFromCallableTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import java.util.List;
import java.util.concurrent.*;

import io.reactivex.exceptions.TestException;
import io.reactivex.plugins.RxJavaPlugins;
import org.junit.Test;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.stubbing.Answer;

import io.reactivex.*;
import io.reactivex.disposables.Disposable;
import io.reactivex.functions.Function;
import io.reactivex.observers.TestObserver;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L38">public class ObservableFromCallableTest {</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void shouldNotInvokeFuncUntilSubscription() throws Exception {
<span class="fc" id="L43">        Callable&lt;Object&gt; func = mock(Callable.class);</span>

<span class="fc" id="L45">        when(func.call()).thenReturn(new Object());</span>

<span class="fc" id="L47">        Observable&lt;Object&gt; fromCallableObservable = Observable.fromCallable(func);</span>

<span class="fc" id="L49">        verifyZeroInteractions(func);</span>

<span class="fc" id="L51">        fromCallableObservable.subscribe();</span>

<span class="fc" id="L53">        verify(func).call();</span>
<span class="fc" id="L54">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void shouldCallOnNextAndOnCompleted() throws Exception {
<span class="fc" id="L59">        Callable&lt;String&gt; func = mock(Callable.class);</span>

<span class="fc" id="L61">        when(func.call()).thenReturn(&quot;test_value&quot;);</span>

<span class="fc" id="L63">        Observable&lt;String&gt; fromCallableObservable = Observable.fromCallable(func);</span>

<span class="fc" id="L65">        Observer&lt;Object&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L67">        fromCallableObservable.subscribe(observer);</span>

<span class="fc" id="L69">        verify(observer).onNext(&quot;test_value&quot;);</span>
<span class="fc" id="L70">        verify(observer).onComplete();</span>
<span class="fc" id="L71">        verify(observer, never()).onError(any(Throwable.class));</span>
<span class="fc" id="L72">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void shouldCallOnError() throws Exception {
<span class="fc" id="L77">        Callable&lt;Object&gt; func = mock(Callable.class);</span>

<span class="fc" id="L79">        Throwable throwable = new IllegalStateException(&quot;Test exception&quot;);</span>
<span class="fc" id="L80">        when(func.call()).thenThrow(throwable);</span>

<span class="fc" id="L82">        Observable&lt;Object&gt; fromCallableObservable = Observable.fromCallable(func);</span>

<span class="fc" id="L84">        Observer&lt;Object&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L86">        fromCallableObservable.subscribe(observer);</span>

<span class="fc" id="L88">        verify(observer, never()).onNext(any());</span>
<span class="fc" id="L89">        verify(observer, never()).onComplete();</span>
<span class="fc" id="L90">        verify(observer).onError(throwable);</span>
<span class="fc" id="L91">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void shouldNotDeliverResultIfSubscriberUnsubscribedBeforeEmission() throws Exception {
<span class="fc" id="L96">        Callable&lt;String&gt; func = mock(Callable.class);</span>

<span class="fc" id="L98">        final CountDownLatch funcLatch = new CountDownLatch(1);</span>
<span class="fc" id="L99">        final CountDownLatch observerLatch = new CountDownLatch(1);</span>

<span class="fc" id="L101">        when(func.call()).thenAnswer(new Answer&lt;String&gt;() {</span>
            @Override
            public String answer(InvocationOnMock invocation) throws Throwable {
<span class="fc" id="L104">                observerLatch.countDown();</span>

                try {
<span class="nc" id="L107">                    funcLatch.await();</span>
<span class="fc" id="L108">                } catch (InterruptedException e) {</span>
                    // It's okay, unsubscription causes Thread interruption

                    // Restoring interruption status of the Thread
<span class="fc" id="L112">                    Thread.currentThread().interrupt();</span>
<span class="nc" id="L113">                }</span>

<span class="fc" id="L115">                return &quot;should_not_be_delivered&quot;;</span>
            }
        });

<span class="fc" id="L119">        Observable&lt;String&gt; fromCallableObservable = Observable.fromCallable(func);</span>

<span class="fc" id="L121">        Observer&lt;Object&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L123">        TestObserver&lt;String&gt; outer = new TestObserver&lt;String&gt;(observer);</span>

<span class="fc" id="L125">        fromCallableObservable</span>
<span class="fc" id="L126">                .subscribeOn(Schedulers.computation())</span>
<span class="fc" id="L127">                .subscribe(outer);</span>

        // Wait until func will be invoked
<span class="fc" id="L130">        observerLatch.await();</span>

        // Unsubscribing before emission
<span class="fc" id="L133">        outer.cancel();</span>

        // Emitting result
<span class="fc" id="L136">        funcLatch.countDown();</span>

        // func must be invoked
<span class="fc" id="L139">        verify(func).call();</span>

        // Observer must not be notified at all
<span class="fc" id="L142">        verify(observer).onSubscribe(any(Disposable.class));</span>
<span class="fc" id="L143">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L144">    }</span>

    @Test
    public void shouldAllowToThrowCheckedException() {
<span class="fc" id="L148">        final Exception checkedException = new Exception(&quot;test exception&quot;);</span>

<span class="fc" id="L150">        Observable&lt;Object&gt; fromCallableObservable = Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L153">                throw checkedException;</span>
            }
        });

<span class="fc" id="L157">        Observer&lt;Object&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L159">        fromCallableObservable.subscribe(observer);</span>

<span class="fc" id="L161">        verify(observer).onSubscribe(any(Disposable.class));</span>
<span class="fc" id="L162">        verify(observer).onError(checkedException);</span>
<span class="fc" id="L163">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L164">    }</span>

    @Test
    public void fusedFlatMapExecution() {
<span class="fc" id="L168">        final int[] calls = { 0 };</span>

<span class="fc" id="L170">        Observable.just(1).flatMap(new Function&lt;Integer, ObservableSource&lt;? extends Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;? extends Object&gt; apply(Integer v)
                    throws Exception {
<span class="fc" id="L174">                return Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
                    @Override
                    public Object call() throws Exception {
<span class="fc" id="L177">                        return ++calls[0];</span>
                    }
                });
            }
        })
<span class="fc" id="L182">        .test()</span>
<span class="fc" id="L183">        .assertResult(1);</span>

<span class="fc" id="L185">        assertEquals(1, calls[0]);</span>
<span class="fc" id="L186">    }</span>

    @Test
    public void fusedFlatMapExecutionHidden() {
<span class="fc" id="L190">        final int[] calls = { 0 };</span>

<span class="fc" id="L192">        Observable.just(1).hide().flatMap(new Function&lt;Integer, ObservableSource&lt;? extends Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;? extends Object&gt; apply(Integer v)
                    throws Exception {
<span class="fc" id="L196">                return Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
                    @Override
                    public Object call() throws Exception {
<span class="fc" id="L199">                        return ++calls[0];</span>
                    }
                });
            }
        })
<span class="fc" id="L204">        .test()</span>
<span class="fc" id="L205">        .assertResult(1);</span>

<span class="fc" id="L207">        assertEquals(1, calls[0]);</span>
<span class="fc" id="L208">    }</span>

    @Test
    public void fusedFlatMapNull() {
<span class="fc" id="L212">        Observable.just(1).flatMap(new Function&lt;Integer, ObservableSource&lt;? extends Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;? extends Object&gt; apply(Integer v)
                    throws Exception {
<span class="fc" id="L216">                return Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
                    @Override
                    public Object call() throws Exception {
<span class="fc" id="L219">                        return null;</span>
                    }
                });
            }
        })
<span class="fc" id="L224">        .test()</span>
<span class="fc" id="L225">        .assertFailure(NullPointerException.class);</span>
<span class="fc" id="L226">    }</span>

    @Test
    public void fusedFlatMapNullHidden() {
<span class="fc" id="L230">        Observable.just(1).hide().flatMap(new Function&lt;Integer, ObservableSource&lt;? extends Object&gt;&gt;() {</span>
            @Override
            public ObservableSource&lt;? extends Object&gt; apply(Integer v)
                    throws Exception {
<span class="fc" id="L234">                return Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
                    @Override
                    public Object call() throws Exception {
<span class="fc" id="L237">                        return null;</span>
                    }
                });
            }
        })
<span class="fc" id="L242">        .test()</span>
<span class="fc" id="L243">        .assertFailure(NullPointerException.class);</span>
<span class="fc" id="L244">    }</span>

    @Test
    public void disposedOnArrival() {
<span class="fc" id="L248">        final int[] count = { 0 };</span>
<span class="fc" id="L249">        Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="nc" id="L252">                count[0]++;</span>
<span class="nc" id="L253">                return 1;</span>
            }
        })
<span class="fc" id="L256">                .test(true)</span>
<span class="fc" id="L257">                .assertEmpty();</span>

<span class="fc" id="L259">        assertEquals(0, count[0]);</span>
<span class="fc" id="L260">    }</span>

    @Test
    public void disposedOnCall() {
<span class="fc" id="L264">        final TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L266">        Observable.fromCallable(new Callable&lt;Integer&gt;() {</span>
            @Override
            public Integer call() throws Exception {
<span class="fc" id="L269">                to.cancel();</span>
<span class="fc" id="L270">                return 1;</span>
            }
        })
<span class="fc" id="L273">                .subscribe(to);</span>

<span class="fc" id="L275">        to.assertEmpty();</span>
<span class="fc" id="L276">    }</span>

    @Test
    public void disposedOnCallThrows() {
<span class="fc" id="L280">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L282">            final TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L284">            Observable.fromCallable(new Callable&lt;Integer&gt;() {</span>
                @Override
                public Integer call() throws Exception {
<span class="fc" id="L287">                    to.cancel();</span>
<span class="fc" id="L288">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L291">                    .subscribe(to);</span>

<span class="fc" id="L293">            to.assertEmpty();</span>

<span class="fc" id="L295">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L297">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L299">    }</span>

    @Test
    public void take() {
<span class="fc" id="L303">        Observable.fromCallable(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L306">                return 1;</span>
            }
        })
<span class="fc" id="L309">                .take(1)</span>
<span class="fc" id="L310">                .test()</span>
<span class="fc" id="L311">                .assertResult(1);</span>
<span class="fc" id="L312">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>