<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableOnErrorResumeNextViaObservableTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableOnErrorResumeNextViaObservableTest.java</span></div><h1>ObservableOnErrorResumeNextViaObservableTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;

import org.junit.*;
import org.mockito.Mockito;

import io.reactivex.*;
import io.reactivex.disposables.Disposable;
import io.reactivex.functions.Function;
import io.reactivex.observers.*;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L28">public class ObservableOnErrorResumeNextViaObservableTest {</span>

    @Test
    public void testResumeNext() {
<span class="fc" id="L32">        Disposable upstream = mock(Disposable.class);</span>
        // Trigger failure on second element
<span class="fc" id="L34">        TestObservable f = new TestObservable(upstream, &quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L35">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L36">        Observable&lt;String&gt; resume = Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L37">        Observable&lt;String&gt; observable = w.onErrorResumeNext(resume);</span>

<span class="fc" id="L39">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L40">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L43">            f.t.join();</span>
<span class="nc" id="L44">        } catch (InterruptedException e) {</span>
<span class="nc" id="L45">            fail(e.getMessage());</span>
<span class="fc" id="L46">        }</span>

<span class="fc" id="L48">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L49">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L50">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L51">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L52">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L53">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L54">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L55">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
<span class="fc" id="L59">        Disposable sr = mock(Disposable.class);</span>
        // Trigger multiple failures
<span class="fc" id="L61">        Observable&lt;String&gt; w = Observable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>
        // Resume Observable is async
<span class="fc" id="L63">        TestObservable f = new TestObservable(sr, &quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L64">        Observable&lt;String&gt; resume = Observable.unsafeCreate(f);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the Observer is a
        //  rx.operator incl onErrorResumeNextViaObservable)
<span class="fc" id="L68">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L71" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L72">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L74">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L75">                return s;</span>
            }
        });

<span class="fc" id="L79">        Observable&lt;String&gt; observable = w.onErrorResumeNext(resume);</span>

<span class="fc" id="L81">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>

<span class="fc" id="L83">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L86">            f.t.join();</span>
<span class="nc" id="L87">        } catch (InterruptedException e) {</span>
<span class="nc" id="L88">            fail(e.getMessage());</span>
<span class="fc" id="L89">        }</span>

<span class="fc" id="L91">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L92">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L93">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L94">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L95">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L96">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L97">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L98">    }</span>

    @Test
    @Ignore(&quot;Publishers should not throw&quot;)
    public void testResumeNextWithFailureOnSubscribe() {
<span class="nc" id="L103">        Observable&lt;String&gt; testObservable = Observable.unsafeCreate(new ObservableSource&lt;String&gt;() {</span>

            @Override
            public void subscribe(Observer&lt;? super String&gt; t1) {
<span class="nc" id="L107">                throw new RuntimeException(&quot;force failure&quot;);</span>
            }

        });
<span class="nc" id="L111">        Observable&lt;String&gt; resume = Observable.just(&quot;resume&quot;);</span>
<span class="nc" id="L112">        Observable&lt;String&gt; observable = testObservable.onErrorResumeNext(resume);</span>

<span class="nc" id="L114">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="nc" id="L115">        observable.subscribe(observer);</span>

<span class="nc" id="L117">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="nc" id="L118">        verify(observer, times(1)).onComplete();</span>
<span class="nc" id="L119">        verify(observer, times(1)).onNext(&quot;resume&quot;);</span>
<span class="nc" id="L120">    }</span>

    @Test
    @Ignore(&quot;Publishers should not throw&quot;)
    public void testResumeNextWithFailureOnSubscribeAsync() {
<span class="nc" id="L125">        Observable&lt;String&gt; testObservable = Observable.unsafeCreate(new ObservableSource&lt;String&gt;() {</span>

            @Override
            public void subscribe(Observer&lt;? super String&gt; t1) {
<span class="nc" id="L129">                throw new RuntimeException(&quot;force failure&quot;);</span>
            }

        });
<span class="nc" id="L133">        Observable&lt;String&gt; resume = Observable.just(&quot;resume&quot;);</span>
<span class="nc" id="L134">        Observable&lt;String&gt; observable = testObservable.subscribeOn(Schedulers.io()).onErrorResumeNext(resume);</span>

<span class="nc" id="L136">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="nc" id="L137">        TestObserver&lt;String&gt; to = new TestObserver&lt;String&gt;(observer);</span>
<span class="nc" id="L138">        observable.subscribe(to);</span>

<span class="nc" id="L140">        to.awaitTerminalEvent();</span>

<span class="nc" id="L142">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="nc" id="L143">        verify(observer, times(1)).onComplete();</span>
<span class="nc" id="L144">        verify(observer, times(1)).onNext(&quot;resume&quot;);</span>
<span class="nc" id="L145">    }</span>

    static class TestObservable implements ObservableSource&lt;String&gt; {

        final Disposable upstream;
        final String[] values;
        Thread t;

<span class="fc" id="L153">        TestObservable(Disposable upstream, String... values) {</span>
<span class="fc" id="L154">            this.upstream = upstream;</span>
<span class="fc" id="L155">            this.values = values;</span>
<span class="fc" id="L156">        }</span>

        @Override
        public void subscribe(final Observer&lt;? super String&gt; observer) {
<span class="fc" id="L160">            System.out.println(&quot;TestObservable subscribed to ...&quot;);</span>
<span class="fc" id="L161">            observer.onSubscribe(upstream);</span>
<span class="fc" id="L162">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L167">                        System.out.println(&quot;running TestObservable thread&quot;);</span>
<span class="fc bfc" id="L168" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc bfc" id="L169" title="All 2 branches covered.">                            if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L170">                                throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                            }
<span class="fc" id="L172">                            System.out.println(&quot;TestObservable onNext: &quot; + s);</span>
<span class="fc" id="L173">                            observer.onNext(s);</span>
                        }
<span class="fc" id="L175">                        System.out.println(&quot;TestObservable onComplete&quot;);</span>
<span class="fc" id="L176">                        observer.onComplete();</span>
<span class="fc" id="L177">                    } catch (Throwable e) {</span>
<span class="fc" id="L178">                        System.out.println(&quot;TestObservable onError: &quot; + e);</span>
<span class="fc" id="L179">                        observer.onError(e);</span>
<span class="fc" id="L180">                    }</span>
<span class="fc" id="L181">                }</span>

            });
<span class="fc" id="L184">            System.out.println(&quot;starting TestObservable thread&quot;);</span>
<span class="fc" id="L185">            t.start();</span>
<span class="fc" id="L186">            System.out.println(&quot;done starting TestObservable thread&quot;);</span>
<span class="fc" id="L187">        }</span>
    }

    @Test
    public void testBackpressure() {
<span class="fc" id="L192">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>
<span class="fc" id="L193">        Observable.range(0, 100000)</span>
<span class="fc" id="L194">                .onErrorResumeNext(Observable.just(1))</span>
<span class="fc" id="L195">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L196">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L201" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L204">                                Thread.sleep(500);</span>
<span class="nc" id="L205">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L206">                                e.printStackTrace();</span>
<span class="fc" id="L207">                            }</span>
                        }
<span class="fc" id="L209">                        return t1;</span>
                    }

                })
<span class="fc" id="L213">                .subscribe(to);</span>
<span class="fc" id="L214">        to.awaitTerminalEvent();</span>
<span class="fc" id="L215">        to.assertNoErrors();</span>
<span class="fc" id="L216">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>