<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>FutureSingleObserverTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.observers</a> &gt; <span class="el_source">FutureSingleObserverTest.java</span></div><h1>FutureSingleObserverTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.observers;

import static io.reactivex.internal.util.ExceptionHelper.timeoutMessage;
import static org.junit.Assert.*;

import java.util.concurrent.*;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.Disposable;
import io.reactivex.exceptions.TestException;
import io.reactivex.internal.functions.Functions;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L30">public class FutureSingleObserverTest {</span>

    @Test
    public void cancel() {
<span class="fc" id="L34">        final Future&lt;?&gt; f = Single.never().toFuture();</span>

<span class="fc" id="L36">        assertFalse(f.isCancelled());</span>
<span class="fc" id="L37">        assertFalse(f.isDone());</span>

<span class="fc" id="L39">        f.cancel(true);</span>

<span class="fc" id="L41">        assertTrue(f.isCancelled());</span>
<span class="fc" id="L42">        assertTrue(f.isDone());</span>

        try {
<span class="nc" id="L45">            f.get();</span>
<span class="nc" id="L46">            fail(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L47">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L49">        } catch (InterruptedException ex) {</span>
<span class="nc" id="L50">            throw new AssertionError(ex);</span>
<span class="nc" id="L51">        } catch (ExecutionException ex) {</span>
<span class="nc" id="L52">            throw new AssertionError(ex);</span>
<span class="pc" id="L53">        }</span>

        try {
<span class="nc" id="L56">            f.get(5, TimeUnit.SECONDS);</span>
<span class="nc" id="L57">            fail(&quot;Should have thrown!&quot;);</span>
<span class="fc" id="L58">        } catch (CancellationException ex) {</span>
            // expected
<span class="nc" id="L60">        } catch (InterruptedException ex) {</span>
<span class="nc" id="L61">            throw new AssertionError(ex);</span>
<span class="nc" id="L62">        } catch (ExecutionException ex) {</span>
<span class="nc" id="L63">            throw new AssertionError(ex);</span>
<span class="nc" id="L64">        } catch (TimeoutException ex) {</span>
<span class="nc" id="L65">            throw new AssertionError(ex);</span>
<span class="pc" id="L66">        }</span>
<span class="fc" id="L67">    }</span>

    @Test
    public void cancelRace() {
<span class="fc bfc" id="L71" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L72">            final Future&lt;?&gt; f = Single.never().toFuture();</span>

<span class="fc" id="L74">            Runnable r = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L77">                    f.cancel(true);</span>
<span class="fc" id="L78">                }</span>
            };

<span class="fc" id="L81">            TestHelper.race(r, r);</span>
        }
<span class="fc" id="L83">    }</span>

    @Test
    public void timeout() throws Exception {

<span class="fc" id="L88">        Future&lt;?&gt; f = Single.never().toFuture();</span>

        try {
<span class="nc" id="L91">            f.get(100, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L92">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L93">        } catch (TimeoutException expected) {</span>
<span class="fc" id="L94">            assertEquals(timeoutMessage(100, TimeUnit.MILLISECONDS), expected.getMessage());</span>
<span class="nc" id="L95">        }</span>
<span class="fc" id="L96">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L100">        Future&lt;Integer&gt; f = Single.just(1).toFuture();</span>

<span class="fc" id="L102">        ((Disposable)f).dispose();</span>

<span class="fc" id="L104">        assertTrue(((Disposable)f).isDisposed());</span>
<span class="fc" id="L105">    }</span>

    @Test
    public void errorGetWithTimeout() throws Exception {
<span class="fc" id="L109">        Future&lt;?&gt; f = Single.error(new TestException()).toFuture();</span>

        try {
<span class="nc" id="L112">            f.get(5, TimeUnit.SECONDS);</span>
<span class="nc" id="L113">            fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L114">        } catch (ExecutionException ex) {</span>
<span class="fc" id="L115">            assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="nc" id="L116">        }</span>
<span class="fc" id="L117">    }</span>

    @Test
    public void normalGetWitHTimeout() throws Exception {
<span class="fc" id="L121">        Future&lt;Integer&gt; f = Single.just(1).toFuture();</span>

<span class="fc" id="L123">        assertEquals(1, f.get(5, TimeUnit.SECONDS).intValue());</span>
<span class="fc" id="L124">    }</span>

    @Test
    public void getAwait() throws Exception {
<span class="fc" id="L128">        Future&lt;Integer&gt; f = Single.just(1).delay(100, TimeUnit.MILLISECONDS).toFuture();</span>

<span class="fc" id="L130">        assertEquals(1, f.get(5, TimeUnit.SECONDS).intValue());</span>
<span class="fc" id="L131">    }</span>

    @Test
    public void onSuccessCancelRace() {
<span class="fc bfc" id="L135" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L136">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L138">            final Future&lt;?&gt; f = ps.single(-99).toFuture();</span>

<span class="fc" id="L140">            ps.onNext(1);</span>

<span class="fc" id="L142">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L145">                    f.cancel(true);</span>
<span class="fc" id="L146">                }</span>
            };

<span class="fc" id="L149">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L152">                    ps.onComplete();</span>
<span class="fc" id="L153">                }</span>
            };

<span class="fc" id="L156">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L158">    }</span>

    @Test
    public void onErrorCancelRace() {
<span class="fc" id="L162">        RxJavaPlugins.setErrorHandler(Functions.emptyConsumer());</span>
        try {
<span class="fc bfc" id="L164" title="All 2 branches covered.">            for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L165">                final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L167">                final Future&lt;?&gt; f = ps.single(-99).toFuture();</span>

<span class="fc" id="L169">                final TestException ex = new TestException();</span>

<span class="fc" id="L171">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L174">                        f.cancel(true);</span>
<span class="fc" id="L175">                    }</span>
                };

<span class="fc" id="L178">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L181">                        ps.onError(ex);</span>
<span class="fc" id="L182">                    }</span>
                };

<span class="fc" id="L185">                TestHelper.race(r1, r2);</span>
            }
        } finally {
<span class="fc" id="L188">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L190">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>