<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>MaybeUsingTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.maybe</a> &gt; <span class="el_source">MaybeUsingTest.java</span></div><h1>MaybeUsingTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.maybe;

import static org.junit.Assert.*;

import java.util.List;
import java.util.concurrent.Callable;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L31">public class MaybeUsingTest {</span>

    @Test
    public void resourceSupplierThrows() {

<span class="fc" id="L36">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L39">                throw new TestException();</span>
            }
<span class="fc" id="L41">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="nc" id="L44">                return Maybe.just(1);</span>
            }
<span class="fc" id="L46">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="nc" id="L50">            }</span>
        })
<span class="fc" id="L52">        .test()</span>
<span class="fc" id="L53">        .assertFailure(TestException.class);</span>
<span class="fc" id="L54">    }</span>

    @Test
    public void errorEager() {

<span class="fc" id="L59">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L62">                return 1;</span>
            }
<span class="fc" id="L64">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L67">                return Maybe.error(new TestException());</span>
            }
<span class="fc" id="L69">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L73">            }</span>
        }, true)
<span class="fc" id="L75">        .test()</span>
<span class="fc" id="L76">        .assertFailure(TestException.class);</span>
<span class="fc" id="L77">    }</span>

    @Test
    public void emptyEager() {

<span class="fc" id="L82">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L85">                return 1;</span>
            }
<span class="fc" id="L87">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L90">                return Maybe.empty();</span>
            }
<span class="fc" id="L92">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L96">            }</span>
        }, true)
<span class="fc" id="L98">        .test()</span>
<span class="fc" id="L99">        .assertResult();</span>
<span class="fc" id="L100">    }</span>

    @Test
    public void errorNonEager() {

<span class="fc" id="L105">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L108">                return 1;</span>
            }
<span class="fc" id="L110">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L113">                return Maybe.error(new TestException());</span>
            }
<span class="fc" id="L115">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L119">            }</span>
        }, false)
<span class="fc" id="L121">        .test()</span>
<span class="fc" id="L122">        .assertFailure(TestException.class);</span>
<span class="fc" id="L123">    }</span>

    @Test
    public void emptyNonEager() {

<span class="fc" id="L128">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L131">                return 1;</span>
            }
<span class="fc" id="L133">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L136">                return Maybe.empty();</span>
            }
<span class="fc" id="L138">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L142">            }</span>
        }, false)
<span class="fc" id="L144">        .test()</span>
<span class="fc" id="L145">        .assertResult();</span>
<span class="fc" id="L146">    }</span>

    @Test
    public void supplierCrashEager() {

<span class="fc" id="L151">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L154">                return 1;</span>
            }
<span class="fc" id="L156">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L159">                throw new TestException();</span>
            }
<span class="fc" id="L161">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L165">            }</span>
        }, true)
<span class="fc" id="L167">        .test()</span>
<span class="fc" id="L168">        .assertFailure(TestException.class);</span>
<span class="fc" id="L169">    }</span>

    @Test
    public void supplierCrashNonEager() {

<span class="fc" id="L174">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L177">                return 1;</span>
            }
<span class="fc" id="L179">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L182">                throw new TestException();</span>
            }
<span class="fc" id="L184">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {

<span class="fc" id="L188">            }</span>
        }, false)
<span class="fc" id="L190">        .test()</span>
<span class="fc" id="L191">        .assertFailure(TestException.class);</span>
<span class="fc" id="L192">    }</span>

    @Test
    public void supplierAndDisposerCrashEager() {
<span class="fc" id="L196">        TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L199">                return 1;</span>
            }
<span class="fc" id="L201">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L204">                throw new TestException(&quot;Main&quot;);</span>
            }
<span class="fc" id="L206">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L209">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L212">        .test()</span>
<span class="fc" id="L213">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L215">        List&lt;Throwable&gt; list = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L217">        TestHelper.assertError(list, 0, TestException.class, &quot;Main&quot;);</span>
<span class="fc" id="L218">        TestHelper.assertError(list, 1, TestException.class, &quot;Disposer&quot;);</span>
<span class="fc" id="L219">    }</span>

    @Test
    public void supplierAndDisposerCrashNonEager() {
<span class="fc" id="L223">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L225">            Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L228">                    return 1;</span>
                }
<span class="fc" id="L230">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L233">                    throw new TestException(&quot;Main&quot;);</span>
                }
<span class="fc" id="L235">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L238">                    throw new TestException(&quot;Disposer&quot;);</span>
                }
            }, false)
<span class="fc" id="L241">            .test()</span>
<span class="fc" id="L242">            .assertFailureAndMessage(TestException.class, &quot;Main&quot;);</span>

<span class="fc" id="L244">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Disposer&quot;);</span>
        } finally {
<span class="fc" id="L246">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L248">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L252">        final int[] call = {0 };</span>

<span class="fc" id="L254">        TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L257">                return 1;</span>
            }
<span class="fc" id="L259">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L262">                return Maybe.never();</span>
            }
<span class="fc" id="L264">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L267">                call[0]++;</span>
<span class="fc" id="L268">            }</span>
        }, false)
<span class="fc" id="L270">        .test();</span>

<span class="fc" id="L272">        to.cancel();</span>

<span class="fc" id="L274">        assertEquals(1, call[0]);</span>
<span class="fc" id="L275">    }</span>

    @Test
    public void disposeCrashes() {
<span class="fc" id="L279">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L281">            TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L284">                    return 1;</span>
                }
<span class="fc" id="L286">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L289">                    return Maybe.never();</span>
                }
<span class="fc" id="L291">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L294">                    throw new TestException();</span>
                }
            }, false)
<span class="fc" id="L297">            .test();</span>

<span class="fc" id="L299">            to.cancel();</span>

<span class="fc" id="L301">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L303">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L305">    }</span>

    @Test
    public void isDisposed() {
<span class="fc" id="L309">        TestHelper.checkDisposed(Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L312">                    return 1;</span>
                }
<span class="fc" id="L314">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L317">                    return Maybe.never();</span>
                }
<span class="fc" id="L319">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="fc" id="L323">                }</span>
            }, false));
<span class="fc" id="L325">    }</span>

    @Test
    public void justDisposerCrashes() {
<span class="fc" id="L329">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L332">                return 1;</span>
            }
<span class="fc" id="L334">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L337">                return Maybe.just(1);</span>
            }
<span class="fc" id="L339">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L342">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L345">        .test()</span>
<span class="fc" id="L346">        .assertFailure(TestException.class);</span>
<span class="fc" id="L347">    }</span>

    @Test
    public void emptyDisposerCrashes() {
<span class="fc" id="L351">        Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L354">                return 1;</span>
            }
<span class="fc" id="L356">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L359">                return Maybe.empty();</span>
            }
<span class="fc" id="L361">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L364">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L367">        .test()</span>
<span class="fc" id="L368">        .assertFailure(TestException.class);</span>
<span class="fc" id="L369">    }</span>

    @Test
    public void errorDisposerCrash() {
<span class="fc" id="L373">        TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
            @Override
            public Object call() throws Exception {
<span class="fc" id="L376">                return 1;</span>
            }
<span class="fc" id="L378">        }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
            @Override
            public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L381">                return Maybe.error(new TestException(&quot;Main&quot;));</span>
            }
<span class="fc" id="L383">        }, new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object d) throws Exception {
<span class="fc" id="L386">                throw new TestException(&quot;Disposer&quot;);</span>
            }
        }, true)
<span class="fc" id="L389">        .test()</span>
<span class="fc" id="L390">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L392">        List&lt;Throwable&gt; list = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L394">        TestHelper.assertError(list, 0, TestException.class, &quot;Main&quot;);</span>
<span class="fc" id="L395">        TestHelper.assertError(list, 1, TestException.class, &quot;Disposer&quot;);</span>
<span class="fc" id="L396">    }</span>

    @Test
    public void doubleOnSubscribe() {
<span class="fc" id="L400">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L402">            Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L405">                    return 1;</span>
                }
<span class="fc" id="L407">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L410">                    return Maybe.wrap(new MaybeSource&lt;Integer&gt;() {</span>
                        @Override
                        public void subscribe(MaybeObserver&lt;? super Integer&gt; observer) {
<span class="fc" id="L413">                            Disposable d1 = Disposables.empty();</span>

<span class="fc" id="L415">                            observer.onSubscribe(d1);</span>

<span class="fc" id="L417">                            Disposable d2 = Disposables.empty();</span>

<span class="fc" id="L419">                            observer.onSubscribe(d2);</span>

<span class="fc" id="L421">                            assertFalse(d1.isDisposed());</span>

<span class="fc" id="L423">                            assertTrue(d2.isDisposed());</span>
<span class="fc" id="L424">                        }</span>
                    });
                }
<span class="fc" id="L427">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="nc" id="L431">                }</span>
<span class="fc" id="L432">            }, false).test();</span>
<span class="fc" id="L433">            TestHelper.assertError(errors, 0, IllegalStateException.class, &quot;Disposable already set!&quot;);</span>
        } finally {
<span class="fc" id="L435">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L437">    }</span>

    @Test
    public void successDisposeRace() {
<span class="fc bfc" id="L441" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L443">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L445">            final TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L448">                    return 1;</span>
                }
<span class="fc" id="L450">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L453">                    return ps.lastElement();</span>
                }
<span class="fc" id="L455">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L458">                }</span>
            }, true)
<span class="fc" id="L460">            .test();</span>

<span class="fc" id="L462">            ps.onNext(1);</span>

<span class="fc" id="L464">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L467">                    to.cancel();</span>
<span class="fc" id="L468">                }</span>
            };

<span class="fc" id="L471">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L474">                    ps.onComplete();</span>
<span class="fc" id="L475">                }</span>
            };

<span class="fc" id="L478">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L480">    }</span>

    @Test
    public void errorDisposeRace() {
<span class="fc bfc" id="L484" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L486">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L488">            final TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L491">                    return 1;</span>
                }
<span class="fc" id="L493">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L496">                    return ps.firstElement();</span>
                }
<span class="fc" id="L498">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {
<span class="fc" id="L501">                }</span>
            }, true)
<span class="fc" id="L503">            .test();</span>

<span class="fc" id="L505">            final TestException ex = new TestException();</span>

<span class="fc" id="L507">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L510">                    to.cancel();</span>
<span class="fc" id="L511">                }</span>
            };

<span class="fc" id="L514">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L517">                    ps.onError(ex);</span>
<span class="fc" id="L518">                }</span>
            };

<span class="fc" id="L521">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L523">    }</span>

    @Test
    public void emptyDisposeRace() {
<span class="fc bfc" id="L527" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>

<span class="fc" id="L529">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L531">            final TestObserver&lt;Integer&gt; to = Maybe.using(new Callable&lt;Object&gt;() {</span>
                @Override
                public Object call() throws Exception {
<span class="fc" id="L534">                    return 1;</span>
                }
<span class="fc" id="L536">            }, new Function&lt;Object, MaybeSource&lt;Integer&gt;&gt;() {</span>
                @Override
                public MaybeSource&lt;Integer&gt; apply(Object v) throws Exception {
<span class="fc" id="L539">                    return ps.firstElement();</span>
                }
<span class="fc" id="L541">            }, new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object d) throws Exception {

<span class="fc" id="L545">                }</span>
            }, true)
<span class="fc" id="L547">            .test();</span>

<span class="fc" id="L549">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L552">                    to.cancel();</span>
<span class="fc" id="L553">                }</span>
            };

<span class="fc" id="L556">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L559">                    ps.onComplete();</span>
<span class="fc" id="L560">                }</span>
            };

<span class="fc" id="L563">            TestHelper.race(r1, r2);</span>
        }
<span class="fc" id="L565">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>