<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>FlowableOnErrorReturnTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.flowable</a> &gt; <span class="el_source">FlowableOnErrorReturnTest.java</span></div><h1>FlowableOnErrorReturnTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.flowable;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

import java.util.concurrent.atomic.AtomicReference;

import org.junit.Test;
import org.mockito.Mockito;
import org.reactivestreams.*;

import io.reactivex.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Function;
import io.reactivex.internal.subscriptions.BooleanSubscription;
import io.reactivex.processors.PublishProcessor;
import io.reactivex.schedulers.Schedulers;
import io.reactivex.subscribers.*;

<span class="fc" id="L33">public class FlowableOnErrorReturnTest {</span>

    @Test
    public void testResumeNext() {
<span class="fc" id="L37">        TestFlowable f = new TestFlowable(&quot;one&quot;);</span>
<span class="fc" id="L38">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L39">        final AtomicReference&lt;Throwable&gt; capturedException = new AtomicReference&lt;Throwable&gt;();</span>

<span class="fc" id="L41">        Flowable&lt;String&gt; flowable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable e) {
<span class="fc" id="L45">                capturedException.set(e);</span>
<span class="fc" id="L46">                return &quot;failure&quot;;</span>
            }

        });

<span class="fc" id="L51">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L52">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L55">            f.t.join();</span>
<span class="nc" id="L56">        } catch (InterruptedException e) {</span>
<span class="nc" id="L57">            fail(e.getMessage());</span>
<span class="fc" id="L58">        }</span>

<span class="fc" id="L60">        verify(subscriber, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L61">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L62">        verify(subscriber, times(1)).onNext(&quot;failure&quot;);</span>
<span class="fc" id="L63">        verify(subscriber, times(1)).onComplete();</span>
<span class="fc" id="L64">        assertNotNull(capturedException.get());</span>
<span class="fc" id="L65">    }</span>

    /**
     * Test that when a function throws an exception this is propagated through onError.
     */
    @Test
    public void testFunctionThrowsError() {
<span class="fc" id="L72">        TestFlowable f = new TestFlowable(&quot;one&quot;);</span>
<span class="fc" id="L73">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L74">        final AtomicReference&lt;Throwable&gt; capturedException = new AtomicReference&lt;Throwable&gt;();</span>

<span class="fc" id="L76">        Flowable&lt;String&gt; flowable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable e) {
<span class="fc" id="L80">                capturedException.set(e);</span>
<span class="fc" id="L81">                throw new RuntimeException(&quot;exception from function&quot;);</span>
            }

        });

<span class="fc" id="L86">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L87">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L90">            f.t.join();</span>
<span class="nc" id="L91">        } catch (InterruptedException e) {</span>
<span class="nc" id="L92">            fail(e.getMessage());</span>
<span class="fc" id="L93">        }</span>

        // we should get the &quot;one&quot; value before the error
<span class="fc" id="L96">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>

        // we should have received an onError call on the Observer since the resume function threw an exception
<span class="fc" id="L99">        verify(subscriber, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L100">        verify(subscriber, times(0)).onComplete();</span>
<span class="fc" id="L101">        assertNotNull(capturedException.get());</span>
<span class="fc" id="L102">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
        // Trigger multiple failures
<span class="fc" id="L107">        Flowable&lt;String&gt; w = Flowable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the observer is a
        //  rx.operator incl onErrorResumeNextViaFlowable)
<span class="fc" id="L111">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L114" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L115">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L117">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L118">                return s;</span>
            }
        });

<span class="fc" id="L122">        Flowable&lt;String&gt; flowable = w.onErrorReturn(new Function&lt;Throwable, String&gt;() {</span>

            @Override
            public String apply(Throwable t1) {
<span class="fc" id="L126">                return &quot;resume&quot;;</span>
            }

        });

<span class="fc" id="L131">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L132">        TestSubscriber&lt;String&gt; ts = new TestSubscriber&lt;String&gt;(subscriber, Long.MAX_VALUE);</span>
<span class="fc" id="L133">        flowable.subscribe(ts);</span>
<span class="fc" id="L134">        ts.awaitTerminalEvent();</span>

<span class="fc" id="L136">        verify(subscriber, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L137">        verify(subscriber, times(1)).onComplete();</span>
<span class="fc" id="L138">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L139">        verify(subscriber, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L140">        verify(subscriber, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L141">        verify(subscriber, times(1)).onNext(&quot;resume&quot;);</span>
<span class="fc" id="L142">    }</span>

    @Test
    public void testBackpressure() {
<span class="fc" id="L146">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L147">        Flowable.range(0, 100000)</span>
<span class="fc" id="L148">                .onErrorReturn(new Function&lt;Throwable, Integer&gt;() {</span>

                    @Override
                    public Integer apply(Throwable t1) {
<span class="nc" id="L152">                        return 1;</span>
                    }

                })
<span class="fc" id="L156">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L157">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L162" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L165">                                Thread.sleep(500);</span>
<span class="nc" id="L166">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L167">                                e.printStackTrace();</span>
<span class="fc" id="L168">                            }</span>
                        }
<span class="fc" id="L170">                        return t1;</span>
                    }

                })
<span class="fc" id="L174">                .subscribe(ts);</span>
<span class="fc" id="L175">        ts.awaitTerminalEvent();</span>
<span class="fc" id="L176">        ts.assertNoErrors();</span>
<span class="fc" id="L177">    }</span>

    private static class TestFlowable implements Publisher&lt;String&gt; {

        final String[] values;
        Thread t;

<span class="fc" id="L184">        TestFlowable(String... values) {</span>
<span class="fc" id="L185">            this.values = values;</span>
<span class="fc" id="L186">        }</span>

        @Override
        public void subscribe(final Subscriber&lt;? super String&gt; subscriber) {
<span class="fc" id="L190">            subscriber.onSubscribe(new BooleanSubscription());</span>
<span class="fc" id="L191">            System.out.println(&quot;TestFlowable subscribed to ...&quot;);</span>
<span class="fc" id="L192">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L197">                        System.out.println(&quot;running TestFlowable thread&quot;);</span>
<span class="fc bfc" id="L198" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc" id="L199">                            System.out.println(&quot;TestFlowable onNext: &quot; + s);</span>
<span class="fc" id="L200">                            subscriber.onNext(s);</span>
                        }
<span class="fc" id="L202">                        throw new RuntimeException(&quot;Forced Failure&quot;);</span>
<span class="fc" id="L203">                    } catch (Throwable e) {</span>
<span class="fc" id="L204">                        subscriber.onError(e);</span>
                    }
<span class="fc" id="L206">                }</span>

            });
<span class="fc" id="L209">            System.out.println(&quot;starting TestFlowable thread&quot;);</span>
<span class="fc" id="L210">            t.start();</span>
<span class="fc" id="L211">            System.out.println(&quot;done starting TestFlowable thread&quot;);</span>
<span class="fc" id="L212">        }</span>
    }

    @Test
    public void normalBackpressure() {
<span class="fc" id="L217">        TestSubscriber&lt;Integer&gt; ts = TestSubscriber.create(0);</span>

<span class="fc" id="L219">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L221">        pp.onErrorReturn(new Function&lt;Throwable, Integer&gt;() {</span>
            @Override
            public Integer apply(Throwable e) {
<span class="fc" id="L224">                return 3;</span>
            }
<span class="fc" id="L226">        }).subscribe(ts);</span>

<span class="fc" id="L228">        ts.request(2);</span>

<span class="fc" id="L230">        pp.onNext(1);</span>
<span class="fc" id="L231">        pp.onNext(2);</span>
<span class="fc" id="L232">        pp.onError(new TestException(&quot;Forced failure&quot;));</span>

<span class="fc" id="L234">        ts.assertValues(1, 2);</span>
<span class="fc" id="L235">        ts.assertNoErrors();</span>
<span class="fc" id="L236">        ts.assertNotComplete();</span>

<span class="fc" id="L238">        ts.request(2);</span>

<span class="fc" id="L240">        ts.assertValues(1, 2, 3);</span>
<span class="fc" id="L241">        ts.assertNoErrors();</span>
<span class="fc" id="L242">        ts.assertComplete();</span>
<span class="fc" id="L243">    }</span>

    @Test
    public void returnItem() {
<span class="fc" id="L247">        Flowable.error(new TestException())</span>
<span class="fc" id="L248">        .onErrorReturnItem(1)</span>
<span class="fc" id="L249">        .test()</span>
<span class="fc" id="L250">        .assertResult(1);</span>
<span class="fc" id="L251">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L255">        TestHelper.checkDisposed(Flowable.just(1).onErrorReturnItem(1));</span>
<span class="fc" id="L256">    }</span>

    @Test
    public void doubleOnSubscribe() {
<span class="fc" id="L260">        TestHelper.checkDoubleOnSubscribeFlowable(new Function&lt;Flowable&lt;Object&gt;, Flowable&lt;Object&gt;&gt;() {</span>
            @Override
            public Flowable&lt;Object&gt; apply(Flowable&lt;Object&gt; f) throws Exception {
<span class="fc" id="L263">                return f.onErrorReturnItem(1);</span>
            }
        });
<span class="fc" id="L266">    }</span>

    @Test
    public void doubleOnError() {
<span class="fc" id="L270">        new Flowable&lt;Integer&gt;() {</span>
            @Override
            protected void subscribeActual(Subscriber&lt;? super Integer&gt; s) {
<span class="fc" id="L273">                s.onSubscribe(new BooleanSubscription());</span>
<span class="fc" id="L274">                s.onError(new TestException());</span>
<span class="fc" id="L275">                s.onError(new TestException());</span>
<span class="fc" id="L276">            }</span>
        }
<span class="fc" id="L278">        .onErrorReturnItem(1)</span>
<span class="fc" id="L279">        .test()</span>
<span class="fc" id="L280">        .assertResult(1);</span>
<span class="fc" id="L281">    }</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>