<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ParallelDoOnNextTryTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.parallel</a> &gt; <span class="el_source">ParallelDoOnNextTryTest.java</span></div><h1>ParallelDoOnNextTryTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.parallel;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subscribers.TestSubscriber;

<span class="fc" id="L29">public class ParallelDoOnNextTryTest implements Consumer&lt;Object&gt; {</span>

    volatile int calls;

    @Override
    public void accept(Object t) throws Exception {
<span class="fc" id="L35">        calls++;</span>
<span class="fc" id="L36">    }</span>

    @Test
    public void doOnNextNoError() {
<span class="fc bfc" id="L40" title="All 2 branches covered.">        for (ParallelFailureHandling e : ParallelFailureHandling.values()) {</span>
<span class="fc" id="L41">            Flowable.just(1)</span>
<span class="fc" id="L42">            .parallel(1)</span>
<span class="fc" id="L43">            .doOnNext(this, e)</span>
<span class="fc" id="L44">            .sequential()</span>
<span class="fc" id="L45">            .test()</span>
<span class="fc" id="L46">            .assertResult(1);</span>

<span class="fc" id="L48">            assertEquals(calls, 1);</span>
<span class="fc" id="L49">            calls = 0;</span>
        }
<span class="fc" id="L51">    }</span>

    @Test
    public void doOnNextErrorNoError() {
<span class="fc bfc" id="L55" title="All 2 branches covered.">        for (ParallelFailureHandling e : ParallelFailureHandling.values()) {</span>
<span class="fc" id="L56">            Flowable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L57">            .parallel(1)</span>
<span class="fc" id="L58">            .doOnNext(this, e)</span>
<span class="fc" id="L59">            .sequential()</span>
<span class="fc" id="L60">            .test()</span>
<span class="fc" id="L61">            .assertFailure(TestException.class);</span>

<span class="fc" id="L63">            assertEquals(calls, 0);</span>
        }
<span class="fc" id="L65">    }</span>

    @Test
    public void doOnNextConditionalNoError() {
<span class="fc bfc" id="L69" title="All 2 branches covered.">        for (ParallelFailureHandling e : ParallelFailureHandling.values()) {</span>
<span class="fc" id="L70">            Flowable.just(1)</span>
<span class="fc" id="L71">            .parallel(1)</span>
<span class="fc" id="L72">            .doOnNext(this, e)</span>
<span class="fc" id="L73">            .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L74">            .sequential()</span>
<span class="fc" id="L75">            .test()</span>
<span class="fc" id="L76">            .assertResult(1);</span>

<span class="fc" id="L78">            assertEquals(calls, 1);</span>
<span class="fc" id="L79">            calls = 0;</span>
        }
<span class="fc" id="L81">    }</span>

    @Test
    public void doOnNextErrorConditionalNoError() {
<span class="fc bfc" id="L85" title="All 2 branches covered.">        for (ParallelFailureHandling e : ParallelFailureHandling.values()) {</span>
<span class="fc" id="L86">            Flowable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L87">            .parallel(1)</span>
<span class="fc" id="L88">            .doOnNext(this, e)</span>
<span class="fc" id="L89">            .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L90">            .sequential()</span>
<span class="fc" id="L91">            .test()</span>
<span class="fc" id="L92">            .assertFailure(TestException.class);</span>

<span class="fc" id="L94">            assertEquals(calls, 0);</span>
        }
<span class="fc" id="L96">    }</span>

    @Test
    public void doOnNextFailWithError() {
<span class="fc" id="L100">        Flowable.range(0, 2)</span>
<span class="fc" id="L101">        .parallel(1)</span>
<span class="fc" id="L102">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L105" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L106">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L108">            }</span>
        }, ParallelFailureHandling.ERROR)
<span class="fc" id="L110">        .sequential()</span>
<span class="fc" id="L111">        .test()</span>
<span class="fc" id="L112">        .assertFailure(ArithmeticException.class);</span>
<span class="fc" id="L113">    }</span>

    @Test
    public void doOnNextFailWithStop() {
<span class="fc" id="L117">        Flowable.range(0, 2)</span>
<span class="fc" id="L118">        .parallel(1)</span>
<span class="fc" id="L119">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L122" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L123">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L125">            }</span>
        }, ParallelFailureHandling.STOP)
<span class="fc" id="L127">        .sequential()</span>
<span class="fc" id="L128">        .test()</span>
<span class="fc" id="L129">        .assertResult();</span>
<span class="fc" id="L130">    }</span>

    @Test
    public void doOnNextFailWithRetry() {
<span class="fc" id="L134">        Flowable.range(0, 2)</span>
<span class="fc" id="L135">        .parallel(1)</span>
<span class="fc" id="L136">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            int count;
            @Override
            public void accept(Integer v) throws Exception {
<span class="fc bfc" id="L140" title="All 2 branches covered.">                if (count++ == 1) {</span>
<span class="fc" id="L141">                    return;</span>
                }
<span class="pc bpc" id="L143" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L144">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L146">            }</span>
        }, ParallelFailureHandling.RETRY)
<span class="fc" id="L148">        .sequential()</span>
<span class="fc" id="L149">        .test()</span>
<span class="fc" id="L150">        .assertResult(0, 1);</span>
<span class="fc" id="L151">    }</span>

    @Test
    public void doOnNextFailWithRetryLimited() {
<span class="fc" id="L155">        Flowable.range(0, 2)</span>
<span class="fc" id="L156">        .parallel(1)</span>
<span class="fc" id="L157">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="pc bpc" id="L160" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L161">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L163">            }</span>
<span class="fc" id="L164">        }, new BiFunction&lt;Long, Throwable, ParallelFailureHandling&gt;() {</span>
            @Override
            public ParallelFailureHandling apply(Long n, Throwable e) throws Exception {
<span class="fc bfc" id="L167" title="All 2 branches covered.">                return n &lt; 5 ? ParallelFailureHandling.RETRY : ParallelFailureHandling.SKIP;</span>
            }
        })
<span class="fc" id="L170">        .sequential()</span>
<span class="fc" id="L171">        .test()</span>
<span class="fc" id="L172">        .assertResult(1);</span>
<span class="fc" id="L173">    }</span>

    @Test
    public void doOnNextFailWithSkip() {
<span class="fc" id="L177">        Flowable.range(0, 2)</span>
<span class="fc" id="L178">        .parallel(1)</span>
<span class="fc" id="L179">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="pc bpc" id="L182" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L183">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L185">            }</span>
        }, ParallelFailureHandling.SKIP)
<span class="fc" id="L187">        .sequential()</span>
<span class="fc" id="L188">        .test()</span>
<span class="fc" id="L189">        .assertResult(1);</span>
<span class="fc" id="L190">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void doOnNextFailHandlerThrows() {
<span class="fc" id="L195">        TestSubscriber&lt;Integer&gt; ts = Flowable.range(0, 2)</span>
<span class="fc" id="L196">        .parallel(1)</span>
<span class="fc" id="L197">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L200" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L201">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L203">            }</span>
<span class="fc" id="L204">        }, new BiFunction&lt;Long, Throwable, ParallelFailureHandling&gt;() {</span>
            @Override
            public ParallelFailureHandling apply(Long n, Throwable e) throws Exception {
<span class="fc" id="L207">                throw new TestException();</span>
            }
        })
<span class="fc" id="L210">        .sequential()</span>
<span class="fc" id="L211">        .test()</span>
<span class="fc" id="L212">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L214">        TestHelper.assertCompositeExceptions(ts, ArithmeticException.class, TestException.class);</span>
<span class="fc" id="L215">    }</span>

    @Test
    public void doOnNextWrongParallelism() {
<span class="fc" id="L219">        TestHelper.checkInvalidParallelSubscribers(</span>
<span class="fc" id="L220">            Flowable.just(1).parallel(1)</span>
<span class="fc" id="L221">            .doOnNext(Functions.emptyConsumer(), ParallelFailureHandling.ERROR)</span>
        );
<span class="fc" id="L223">    }</span>

    @Test
    public void filterInvalidSource() {
<span class="fc" id="L227">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L229">            new ParallelInvalid()</span>
<span class="fc" id="L230">            .doOnNext(Functions.emptyConsumer(), ParallelFailureHandling.ERROR)</span>
<span class="fc" id="L231">            .sequential()</span>
<span class="fc" id="L232">            .test();</span>

<span class="fc" id="L234">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L236">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L238">    }</span>

    @Test
    public void doOnNextFailWithErrorConditional() {
<span class="fc" id="L242">        Flowable.range(0, 2)</span>
<span class="fc" id="L243">        .parallel(1)</span>
<span class="fc" id="L244">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L247" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L248">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L250">            }</span>
        }, ParallelFailureHandling.ERROR)
<span class="fc" id="L252">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L253">        .sequential()</span>
<span class="fc" id="L254">        .test()</span>
<span class="fc" id="L255">        .assertFailure(ArithmeticException.class);</span>
<span class="fc" id="L256">    }</span>

    @Test
    public void doOnNextFailWithStopConditional() {
<span class="fc" id="L260">        Flowable.range(0, 2)</span>
<span class="fc" id="L261">        .parallel(1)</span>
<span class="fc" id="L262">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L265" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L266">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L268">            }</span>
        }, ParallelFailureHandling.STOP)
<span class="fc" id="L270">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L271">        .sequential()</span>
<span class="fc" id="L272">        .test()</span>
<span class="fc" id="L273">        .assertResult();</span>
<span class="fc" id="L274">    }</span>

    @Test
    public void doOnNextFailWithRetryConditional() {
<span class="fc" id="L278">        Flowable.range(0, 2)</span>
<span class="fc" id="L279">        .parallel(1)</span>
<span class="fc" id="L280">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            int count;
            @Override
            public void accept(Integer v) throws Exception {
<span class="fc bfc" id="L284" title="All 2 branches covered.">                if (count++ == 1) {</span>
<span class="fc" id="L285">                    return;</span>
                }
<span class="pc bpc" id="L287" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L288">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L290">            }</span>
        }, ParallelFailureHandling.RETRY)
<span class="fc" id="L292">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L293">        .sequential()</span>
<span class="fc" id="L294">        .test()</span>
<span class="fc" id="L295">        .assertResult(0, 1);</span>
<span class="fc" id="L296">    }</span>

    @Test
    public void doOnNextFailWithRetryLimitedConditional() {
<span class="fc" id="L300">        Flowable.range(0, 2)</span>
<span class="fc" id="L301">        .parallel(1)</span>
<span class="fc" id="L302">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="pc bpc" id="L305" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L306">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L308">            }</span>
<span class="fc" id="L309">        }, new BiFunction&lt;Long, Throwable, ParallelFailureHandling&gt;() {</span>
            @Override
            public ParallelFailureHandling apply(Long n, Throwable e) throws Exception {
<span class="fc bfc" id="L312" title="All 2 branches covered.">                return n &lt; 5 ? ParallelFailureHandling.RETRY : ParallelFailureHandling.SKIP;</span>
            }
        })
<span class="fc" id="L315">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L316">        .sequential()</span>
<span class="fc" id="L317">        .test()</span>
<span class="fc" id="L318">        .assertResult(1);</span>
<span class="fc" id="L319">    }</span>

    @Test
    public void doOnNextFailWithSkipConditional() {
<span class="fc" id="L323">        Flowable.range(0, 2)</span>
<span class="fc" id="L324">        .parallel(1)</span>
<span class="fc" id="L325">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="pc bpc" id="L328" title="1 of 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L329">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="fc" id="L331">            }</span>
        }, ParallelFailureHandling.SKIP)
<span class="fc" id="L333">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L334">        .sequential()</span>
<span class="fc" id="L335">        .test()</span>
<span class="fc" id="L336">        .assertResult(1);</span>
<span class="fc" id="L337">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void doOnNextFailHandlerThrowsConditional() {
<span class="fc" id="L342">        TestSubscriber&lt;Integer&gt; ts = Flowable.range(0, 2)</span>
<span class="fc" id="L343">        .parallel(1)</span>
<span class="fc" id="L344">        .doOnNext(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc bnc" id="L347" title="All 2 branches missed.">                if (1 / v &lt; 0) {</span>
<span class="nc" id="L348">                    System.out.println(&quot;Should not happen!&quot;);</span>
                }
<span class="nc" id="L350">            }</span>
<span class="fc" id="L351">        }, new BiFunction&lt;Long, Throwable, ParallelFailureHandling&gt;() {</span>
            @Override
            public ParallelFailureHandling apply(Long n, Throwable e) throws Exception {
<span class="fc" id="L354">                throw new TestException();</span>
            }
        })
<span class="fc" id="L357">        .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L358">        .sequential()</span>
<span class="fc" id="L359">        .test()</span>
<span class="fc" id="L360">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L362">        TestHelper.assertCompositeExceptions(ts, ArithmeticException.class, TestException.class);</span>
<span class="fc" id="L363">    }</span>

    @Test
    public void doOnNextWrongParallelismConditional() {
<span class="fc" id="L367">        TestHelper.checkInvalidParallelSubscribers(</span>
<span class="fc" id="L368">            Flowable.just(1).parallel(1)</span>
<span class="fc" id="L369">            .doOnNext(Functions.emptyConsumer(), ParallelFailureHandling.ERROR)</span>
<span class="fc" id="L370">            .filter(Functions.alwaysTrue())</span>
        );
<span class="fc" id="L372">    }</span>

    @Test
    public void filterInvalidSourceConditional() {
<span class="fc" id="L376">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L378">            new ParallelInvalid()</span>
<span class="fc" id="L379">            .doOnNext(Functions.emptyConsumer(), ParallelFailureHandling.ERROR)</span>
<span class="fc" id="L380">            .filter(Functions.alwaysTrue())</span>
<span class="fc" id="L381">            .sequential()</span>
<span class="fc" id="L382">            .test();</span>

<span class="fc" id="L384">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L386">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L388">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>