<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ParallelCollectTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.parallel</a> &gt; <span class="el_source">ParallelCollectTest.java</span></div><h1>ParallelCollectTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.parallel;

import static org.junit.Assert.*;

import java.util.*;
import java.util.concurrent.Callable;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.*;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.processors.PublishProcessor;
import io.reactivex.subscribers.TestSubscriber;

<span class="fc" id="L30">public class ParallelCollectTest {</span>

    @Test
    public void subscriberCount() {
<span class="fc" id="L34">        ParallelFlowableTest.checkSubscriberCount(Flowable.range(1, 5).parallel()</span>
<span class="fc" id="L35">        .collect(new Callable&lt;List&lt;Integer&gt;&gt;() {</span>
            @Override
            public List&lt;Integer&gt; call() throws Exception {
<span class="nc" id="L38">                return new ArrayList&lt;Integer&gt;();</span>
            }
<span class="fc" id="L40">        }, new BiConsumer&lt;List&lt;Integer&gt;, Integer&gt;() {</span>
            @Override
            public void accept(List&lt;Integer&gt; a, Integer b) throws Exception {
<span class="nc" id="L43">                a.add(b);</span>
<span class="nc" id="L44">            }</span>
        }));
<span class="fc" id="L46">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void initialCrash() {
<span class="fc" id="L51">        Flowable.range(1, 5)</span>
<span class="fc" id="L52">        .parallel()</span>
<span class="fc" id="L53">        .collect(new Callable&lt;List&lt;Integer&gt;&gt;() {</span>
            @Override
            public List&lt;Integer&gt; call() throws Exception {
<span class="fc" id="L56">                throw new TestException();</span>
            }
<span class="fc" id="L58">        }, new BiConsumer&lt;List&lt;Integer&gt;, Integer&gt;() {</span>
            @Override
            public void accept(List&lt;Integer&gt; a, Integer b) throws Exception {
<span class="nc" id="L61">                a.add(b);</span>
<span class="nc" id="L62">            }</span>
        })
<span class="fc" id="L64">        .sequential()</span>
<span class="fc" id="L65">        .test()</span>
<span class="fc" id="L66">        .assertFailure(TestException.class);</span>
<span class="fc" id="L67">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void reducerCrash() {
<span class="fc" id="L72">        Flowable.range(1, 5)</span>
<span class="fc" id="L73">        .parallel()</span>
<span class="fc" id="L74">        .collect(new Callable&lt;List&lt;Integer&gt;&gt;() {</span>
            @Override
            public List&lt;Integer&gt; call() throws Exception {
<span class="fc" id="L77">                return new ArrayList&lt;Integer&gt;();</span>
            }
<span class="fc" id="L79">        }, new BiConsumer&lt;List&lt;Integer&gt;, Integer&gt;() {</span>
            @Override
            public void accept(List&lt;Integer&gt; a, Integer b) throws Exception {
<span class="fc bfc" id="L82" title="All 2 branches covered.">                if (b == 3) {</span>
<span class="fc" id="L83">                    throw new TestException();</span>
                }
<span class="fc" id="L85">                a.add(b);</span>
<span class="fc" id="L86">            }</span>
        })
<span class="fc" id="L88">        .sequential()</span>
<span class="fc" id="L89">        .test()</span>
<span class="fc" id="L90">        .assertFailure(TestException.class);</span>
<span class="fc" id="L91">    }</span>

    @Test
    public void cancel() {
<span class="fc" id="L95">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L97">        TestSubscriber&lt;List&lt;Integer&gt;&gt; ts = pp</span>
<span class="fc" id="L98">        .parallel()</span>
<span class="fc" id="L99">        .collect(new Callable&lt;List&lt;Integer&gt;&gt;() {</span>
            @Override
            public List&lt;Integer&gt; call() throws Exception {
<span class="fc" id="L102">                return new ArrayList&lt;Integer&gt;();</span>
            }
<span class="fc" id="L104">        }, new BiConsumer&lt;List&lt;Integer&gt;, Integer&gt;() {</span>
            @Override
            public void accept(List&lt;Integer&gt; a, Integer b) throws Exception {
<span class="nc" id="L107">                a.add(b);</span>
<span class="nc" id="L108">            }</span>
        })
<span class="fc" id="L110">        .sequential()</span>
<span class="fc" id="L111">        .test();</span>

<span class="fc" id="L113">        assertTrue(pp.hasSubscribers());</span>

<span class="fc" id="L115">        ts.cancel();</span>

<span class="fc" id="L117">        assertFalse(pp.hasSubscribers());</span>
<span class="fc" id="L118">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void error() {
<span class="fc" id="L123">        Flowable.&lt;Integer&gt;error(new TestException())</span>
<span class="fc" id="L124">        .parallel()</span>
<span class="fc" id="L125">        .collect(new Callable&lt;List&lt;Integer&gt;&gt;() {</span>
            @Override
            public List&lt;Integer&gt; call() throws Exception {
<span class="fc" id="L128">                return new ArrayList&lt;Integer&gt;();</span>
            }
<span class="fc" id="L130">        }, new BiConsumer&lt;List&lt;Integer&gt;, Integer&gt;() {</span>
            @Override
            public void accept(List&lt;Integer&gt; a, Integer b) throws Exception {
<span class="nc" id="L133">                a.add(b);</span>
<span class="nc" id="L134">            }</span>
        })
<span class="fc" id="L136">        .sequential()</span>
<span class="fc" id="L137">        .test()</span>
<span class="fc" id="L138">        .assertFailure(TestException.class);</span>
<span class="fc" id="L139">    }</span>

    @SuppressWarnings(&quot;unchecked&quot;)
    @Test
    public void doubleError() {
<span class="fc" id="L144">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L146">            new ParallelInvalid()</span>
<span class="fc" id="L147">            .collect(new Callable&lt;List&lt;Object&gt;&gt;() {</span>
                @Override
                public List&lt;Object&gt; call() throws Exception {
<span class="fc" id="L150">                    return new ArrayList&lt;Object&gt;();</span>
                }
<span class="fc" id="L152">            }, new BiConsumer&lt;List&lt;Object&gt;, Object&gt;() {</span>
                @Override
                public void accept(List&lt;Object&gt; a, Object b) throws Exception {
<span class="nc" id="L155">                    a.add(b);</span>
<span class="nc" id="L156">                }</span>
            })
<span class="fc" id="L158">            .sequential()</span>
<span class="fc" id="L159">            .test()</span>
<span class="fc" id="L160">            .assertFailure(TestException.class);</span>

<span class="fc" id="L162">            assertFalse(errors.isEmpty());</span>
<span class="fc bfc" id="L163" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L164">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L165">            }</span>
        } finally {
<span class="fc" id="L167">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L169">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>