<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ParallelPeekTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.parallel</a> &gt; <span class="el_source">ParallelPeekTest.java</span></div><h1>ParallelPeekTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.parallel;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.List;

import org.junit.Test;
import org.reactivestreams.Subscription;

import io.reactivex.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.plugins.RxJavaPlugins;

<span class="fc" id="L30">public class ParallelPeekTest {</span>

    @Test
    public void subscriberCount() {
<span class="fc" id="L34">        ParallelFlowableTest.checkSubscriberCount(Flowable.range(1, 5).parallel()</span>
<span class="fc" id="L35">        .doOnNext(Functions.emptyConsumer()));</span>
<span class="fc" id="L36">    }</span>

    @Test
    public void onSubscribeCrash() {
<span class="fc" id="L40">        Flowable.range(1, 5)</span>
<span class="fc" id="L41">        .parallel()</span>
<span class="fc" id="L42">        .doOnSubscribe(new Consumer&lt;Subscription&gt;() {</span>
            @Override
            public void accept(Subscription s) throws Exception {
<span class="fc" id="L45">                throw new TestException();</span>
            }
        })
<span class="fc" id="L48">        .sequential()</span>
<span class="fc" id="L49">        .test()</span>
<span class="fc" id="L50">        .assertFailure(TestException.class);</span>
<span class="fc" id="L51">    }</span>

    @Test
    public void doubleError() {
<span class="fc" id="L55">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L57">            new ParallelInvalid()</span>
<span class="fc" id="L58">            .doOnNext(Functions.emptyConsumer())</span>
<span class="fc" id="L59">            .sequential()</span>
<span class="fc" id="L60">            .test()</span>
<span class="fc" id="L61">            .assertFailure(TestException.class);</span>

<span class="fc" id="L63">            assertFalse(errors.isEmpty());</span>
<span class="fc bfc" id="L64" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L65">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L66">            }</span>
        } finally {
<span class="fc" id="L68">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L70">    }</span>

    @Test
    public void requestCrash() {
<span class="fc" id="L74">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L77">            Flowable.range(1, 5)</span>
<span class="fc" id="L78">            .parallel()</span>
<span class="fc" id="L79">            .doOnRequest(new LongConsumer() {</span>
                @Override
                public void accept(long n) throws Exception {
<span class="fc" id="L82">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L85">            .sequential()</span>
<span class="fc" id="L86">            .test()</span>
<span class="fc" id="L87">            .assertResult(1, 2, 3, 4, 5);</span>

<span class="fc" id="L89">            assertFalse(errors.isEmpty());</span>

<span class="fc bfc" id="L91" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L92">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L93">            }</span>
        } finally {
<span class="fc" id="L95">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L97">    }</span>

    @Test
    public void cancelCrash() {
<span class="fc" id="L101">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L104">            Flowable.&lt;Integer&gt;never()</span>
<span class="fc" id="L105">            .parallel()</span>
<span class="fc" id="L106">            .doOnCancel(new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L109">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L112">            .sequential()</span>
<span class="fc" id="L113">            .test()</span>
<span class="fc" id="L114">            .cancel();</span>

<span class="fc" id="L116">            assertFalse(errors.isEmpty());</span>

<span class="fc bfc" id="L118" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L119">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L120">            }</span>
        } finally {
<span class="fc" id="L122">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L124">    }</span>

    @Test
    public void onCompleteCrash() {
<span class="fc" id="L128">        Flowable.just(1)</span>
<span class="fc" id="L129">        .parallel()</span>
<span class="fc" id="L130">        .doOnComplete(new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="fc" id="L133">                throw new TestException();</span>
            }
        })
<span class="fc" id="L136">        .sequential()</span>
<span class="fc" id="L137">        .test()</span>
<span class="fc" id="L138">        .assertFailure(TestException.class, 1);</span>
<span class="fc" id="L139">    }</span>

    @Test
    public void onAfterTerminatedCrash() {
<span class="fc" id="L143">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L146">            Flowable.just(1)</span>
<span class="fc" id="L147">            .parallel()</span>
<span class="fc" id="L148">            .doAfterTerminated(new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L151">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L154">            .sequential()</span>
<span class="fc" id="L155">            .test()</span>
<span class="fc" id="L156">            .assertResult(1);</span>

<span class="fc" id="L158">            assertFalse(errors.isEmpty());</span>

<span class="fc bfc" id="L160" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L161">                assertTrue(ex.toString(), ex.getCause() instanceof TestException);</span>
<span class="fc" id="L162">            }</span>
        } finally {
<span class="fc" id="L164">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L166">    }</span>

    @Test
    public void onAfterTerminatedCrash2() {
<span class="fc" id="L170">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L173">            Flowable.&lt;Integer&gt;error(new IOException())</span>
<span class="fc" id="L174">            .parallel()</span>
<span class="fc" id="L175">            .doAfterTerminated(new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L178">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L181">            .sequential()</span>
<span class="fc" id="L182">            .test()</span>
<span class="fc" id="L183">            .assertFailure(IOException.class);</span>

<span class="fc" id="L185">            assertFalse(errors.isEmpty());</span>

<span class="fc bfc" id="L187" title="All 2 branches covered.">            for (Throwable ex : errors) {</span>
<span class="fc" id="L188">                Throwable exc = ex.getCause();</span>
<span class="pc bpc" id="L189" title="3 of 4 branches missed.">                assertTrue(ex.toString(), exc instanceof TestException</span>
                        || exc instanceof IOException);
<span class="fc" id="L191">            }</span>
        } finally {
<span class="fc" id="L193">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L195">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>