<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>SingleSubscribeTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.single</a> &gt; <span class="el_source">SingleSubscribeTest.java</span></div><h1>SingleSubscribeTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.single;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.List;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.Disposable;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L31">public class SingleSubscribeTest {</span>

    @Test
    public void consumer() {
<span class="fc" id="L35">        final Integer[] value = { null };</span>

<span class="fc" id="L37">        Single.just(1).subscribe(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="fc" id="L40">                value[0] = v;</span>
<span class="fc" id="L41">            }</span>
        });

<span class="fc" id="L44">        assertEquals((Integer)1, value[0]);</span>
<span class="fc" id="L45">    }</span>

    @Test
    public void biconsumer() {
<span class="fc" id="L49">        final Object[] value = { null, null };</span>

<span class="fc" id="L51">        Single.just(1).subscribe(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
            @Override
            public void accept(Integer v, Throwable e) throws Exception {
<span class="fc" id="L54">                value[0] = v;</span>
<span class="fc" id="L55">                value[1] = e;</span>
<span class="fc" id="L56">            }</span>
        });

<span class="fc" id="L59">        assertEquals(1, value[0]);</span>
<span class="fc" id="L60">        assertNull(value[1]);</span>
<span class="fc" id="L61">    }</span>

    @Test
    public void biconsumerError() {
<span class="fc" id="L65">        final Object[] value = { null, null };</span>

<span class="fc" id="L67">        TestException ex = new TestException();</span>

<span class="fc" id="L69">        Single.error(ex).subscribe(new BiConsumer&lt;Object, Throwable&gt;() {</span>
            @Override
            public void accept(Object v, Throwable e) throws Exception {
<span class="fc" id="L72">                value[0] = v;</span>
<span class="fc" id="L73">                value[1] = e;</span>
<span class="fc" id="L74">            }</span>
        });

<span class="fc" id="L77">        assertNull(value[0]);</span>
<span class="fc" id="L78">        assertEquals(ex, value[1]);</span>
<span class="fc" id="L79">    }</span>

    @Test
    public void subscribeThrows() {
        try {
<span class="fc" id="L84">            new Single&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(SingleObserver&lt;? super Integer&gt; observer) {
<span class="fc" id="L87">                    throw new IllegalArgumentException();</span>
                }
<span class="nc" id="L89">            }.test();</span>
<span class="fc" id="L90">        } catch (NullPointerException ex) {</span>
<span class="pc bpc" id="L91" title="1 of 2 branches missed.">            if (!(ex.getCause() instanceof IllegalArgumentException)) {</span>
<span class="nc" id="L92">                fail(ex.toString() + &quot;: should have thrown NPE(IAE)&quot;);</span>
            }
<span class="nc" id="L94">        }</span>
<span class="fc" id="L95">    }</span>

    @Test
    public void biConsumerDispose() {
<span class="fc" id="L99">        PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L101">        Disposable d = ps.single(-99).subscribe(new BiConsumer&lt;Object, Object&gt;() {</span>
            @Override
            public void accept(Object t1, Object t2) throws Exception {

<span class="nc" id="L105">            }</span>
        });

<span class="fc" id="L108">        assertFalse(d.isDisposed());</span>

<span class="fc" id="L110">        d.dispose();</span>

<span class="fc" id="L112">        assertTrue(d.isDisposed());</span>

<span class="fc" id="L114">        assertFalse(ps.hasObservers());</span>
<span class="fc" id="L115">    }</span>

    @Test
    public void consumerDispose() {
<span class="fc" id="L119">        PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L121">        Disposable d = ps.single(-99).subscribe(Functions.&lt;Integer&gt;emptyConsumer());</span>

<span class="fc" id="L123">        assertFalse(d.isDisposed());</span>

<span class="fc" id="L125">        d.dispose();</span>

<span class="fc" id="L127">        assertTrue(d.isDisposed());</span>

<span class="fc" id="L129">        assertFalse(ps.hasObservers());</span>
<span class="fc" id="L130">    }</span>

    @Test
    public void consumerSuccessThrows() {
<span class="fc" id="L134">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L137">            Single.just(1).subscribe(new Consumer&lt;Integer&gt;() {</span>
                @Override
                public void accept(Integer t) throws Exception {
<span class="fc" id="L140">                    throw new TestException();</span>
                }
            });

<span class="fc" id="L144">            TestHelper.assertUndeliverable(list, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L146">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L148">    }</span>

    @Test
    public void consumerErrorThrows() {
<span class="fc" id="L152">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L155">            Single.&lt;Integer&gt;error(new TestException(&quot;Outer failure&quot;)).subscribe(</span>
<span class="fc" id="L156">            Functions.&lt;Integer&gt;emptyConsumer(),</span>
<span class="fc" id="L157">            new Consumer&lt;Throwable&gt;() {</span>
                @Override
                public void accept(Throwable t) throws Exception {
<span class="fc" id="L160">                    throw new TestException(&quot;Inner failure&quot;);</span>
                }
            });

<span class="fc" id="L164">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L165">            List&lt;Throwable&gt; cel = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L166">            TestHelper.assertError(cel, 0, TestException.class, &quot;Outer failure&quot;);</span>
<span class="fc" id="L167">            TestHelper.assertError(cel, 1, TestException.class, &quot;Inner failure&quot;);</span>
        } finally {
<span class="fc" id="L169">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L171">    }</span>

    @Test
    public void biConsumerThrows() {
<span class="fc" id="L175">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L178">            Single.just(1).subscribe(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
                @Override
                public void accept(Integer t, Throwable e) throws Exception {
<span class="fc" id="L181">                    throw new TestException();</span>
                }
            });

<span class="fc" id="L185">            TestHelper.assertUndeliverable(list, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L187">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L189">    }</span>

    @Test
    public void biConsumerErrorThrows() {
<span class="fc" id="L193">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L196">            Single.&lt;Integer&gt;error(new TestException(&quot;Outer failure&quot;)).subscribe(</span>
<span class="fc" id="L197">            new BiConsumer&lt;Integer, Throwable&gt;() {</span>
                @Override
                public void accept(Integer a, Throwable t) throws Exception {
<span class="fc" id="L200">                    throw new TestException(&quot;Inner failure&quot;);</span>
                }
            });

<span class="fc" id="L204">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L205">            List&lt;Throwable&gt; cel = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L206">            TestHelper.assertError(cel, 0, TestException.class, &quot;Outer failure&quot;);</span>
<span class="fc" id="L207">            TestHelper.assertError(cel, 1, TestException.class, &quot;Inner failure&quot;);</span>
        } finally {
<span class="fc" id="L209">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L211">    }</span>

    @Test
    public void methodTestNoCancel() {
<span class="fc" id="L215">        PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L217">        ps.single(-99).test(false);</span>

<span class="fc" id="L219">        assertTrue(ps.hasObservers());</span>
<span class="fc" id="L220">    }</span>

    @Test
    public void successIsDisposed() {
<span class="fc" id="L224">        assertTrue(Single.just(1).subscribe().isDisposed());</span>
<span class="fc" id="L225">    }</span>

    @Test
    public void errorIsDisposed() {
<span class="fc" id="L229">        assertTrue(Single.error(new TestException()).subscribe(Functions.emptyConsumer(), Functions.emptyConsumer()).isDisposed());</span>
<span class="fc" id="L230">    }</span>

    @Test
    public void biConsumerIsDisposedOnSuccess() {
<span class="fc" id="L234">        final Object[] result = { null, null };</span>

<span class="fc" id="L236">        Disposable d = Single.just(1)</span>
<span class="fc" id="L237">        .subscribe(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
            @Override
            public void accept(Integer t1, Throwable t2) throws Exception {
<span class="fc" id="L240">                result[0] = t1;</span>
<span class="fc" id="L241">                result[1] = t2;</span>
<span class="fc" id="L242">            }</span>
        });

<span class="fc" id="L245">        assertTrue(&quot;Not disposed?!&quot;, d.isDisposed());</span>
<span class="fc" id="L246">        assertEquals(1, result[0]);</span>
<span class="fc" id="L247">        assertNull(result[1]);</span>
<span class="fc" id="L248">    }</span>

    @Test
    public void biConsumerIsDisposedOnError() {
<span class="fc" id="L252">        final Object[] result = { null, null };</span>

<span class="fc" id="L254">        Disposable d = Single.&lt;Integer&gt;error(new IOException())</span>
<span class="fc" id="L255">        .subscribe(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
            @Override
            public void accept(Integer t1, Throwable t2) throws Exception {
<span class="fc" id="L258">                result[0] = t1;</span>
<span class="fc" id="L259">                result[1] = t2;</span>
<span class="fc" id="L260">            }</span>
        });

<span class="fc" id="L263">        assertTrue(&quot;Not disposed?!&quot;, d.isDisposed());</span>
<span class="fc" id="L264">        assertNull(result[0]);</span>
<span class="fc" id="L265">        assertTrue(&quot;&quot; + result[1], result[1] instanceof IOException);</span>
<span class="fc" id="L266">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>