<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>CompletableMergeTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.completable</a> &gt; <span class="el_source">CompletableMergeTest.java</span></div><h1>CompletableMergeTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.completable;

import static org.junit.Assert.*;

import java.util.*;

import org.junit.Test;
import org.reactivestreams.Subscriber;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.Function;
import io.reactivex.internal.subscriptions.BooleanSubscription;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.processors.PublishProcessor;

<span class="fc" id="L32">public class CompletableMergeTest {</span>
    @Test
    public void invalidPrefetch() {
        try {
<span class="nc" id="L36">            Completable.merge(Flowable.just(Completable.complete()), -99);</span>
<span class="nc" id="L37">            fail(&quot;Should have thrown IllegalArgumentExceptio&quot;);</span>
<span class="fc" id="L38">        } catch (IllegalArgumentException ex) {</span>
<span class="fc" id="L39">            assertEquals(&quot;maxConcurrency &gt; 0 required but it was -99&quot;, ex.getMessage());</span>
<span class="nc" id="L40">        }</span>
<span class="fc" id="L41">    }</span>

    @Test
    public void cancelAfterFirst() {
<span class="fc" id="L45">        final TestObserver&lt;Void&gt; to = new TestObserver&lt;Void&gt;();</span>

<span class="fc" id="L47">        Completable.mergeArray(new Completable() {</span>
            @Override
            protected void subscribeActual(CompletableObserver observer) {
<span class="fc" id="L50">                observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L51">                observer.onComplete();</span>
<span class="fc" id="L52">                to.cancel();</span>
<span class="fc" id="L53">            }</span>
<span class="fc" id="L54">        }, Completable.complete())</span>
<span class="fc" id="L55">        .subscribe(to);</span>

<span class="fc" id="L57">        to.assertEmpty();</span>
<span class="fc" id="L58">    }</span>

    @Test
    public void cancelAfterFirstDelayError() {
<span class="fc" id="L62">        final TestObserver&lt;Void&gt; to = new TestObserver&lt;Void&gt;();</span>

<span class="fc" id="L64">        Completable.mergeArrayDelayError(new Completable() {</span>
            @Override
            protected void subscribeActual(CompletableObserver observer) {
<span class="fc" id="L67">                observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L68">                observer.onComplete();</span>
<span class="fc" id="L69">                to.cancel();</span>
<span class="fc" id="L70">            }</span>
<span class="fc" id="L71">        }, Completable.complete())</span>
<span class="fc" id="L72">        .subscribe(to);</span>

<span class="fc" id="L74">        to.assertEmpty();</span>
<span class="fc" id="L75">    }</span>

    @Test
    public void onErrorAfterComplete() {
<span class="fc" id="L79">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L81">            final CompletableObserver[] co = { null };</span>

<span class="fc" id="L83">            Completable.mergeArrayDelayError(Completable.complete(), new Completable() {</span>
                @Override
                protected void subscribeActual(CompletableObserver observer) {
<span class="fc" id="L86">                    observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L87">                    observer.onComplete();</span>
<span class="fc" id="L88">                    co[0] = observer;</span>
<span class="fc" id="L89">                }</span>
            })
<span class="fc" id="L91">            .test()</span>
<span class="fc" id="L92">            .assertResult();</span>

<span class="fc" id="L94">            co[0].onError(new TestException());</span>

<span class="fc" id="L96">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L98">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L100">    }</span>

    @Test
    public void completeAfterMain() {
<span class="fc" id="L104">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L106">        TestObserver&lt;Void&gt; to = Completable.mergeArray(Completable.complete(), pp.ignoreElements())</span>
<span class="fc" id="L107">        .test();</span>

<span class="fc" id="L109">        pp.onComplete();</span>

<span class="fc" id="L111">        to.assertResult();</span>
<span class="fc" id="L112">    }</span>

    @Test
    public void completeAfterMainDelayError() {
<span class="fc" id="L116">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L118">        TestObserver&lt;Void&gt; to = Completable.mergeArrayDelayError(Completable.complete(), pp.ignoreElements())</span>
<span class="fc" id="L119">        .test();</span>

<span class="fc" id="L121">        pp.onComplete();</span>

<span class="fc" id="L123">        to.assertResult();</span>
<span class="fc" id="L124">    }</span>

    @Test
    public void errorAfterMainDelayError() {
<span class="fc" id="L128">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L130">        TestObserver&lt;Void&gt; to = Completable.mergeArrayDelayError(Completable.complete(), pp.ignoreElements())</span>
<span class="fc" id="L131">        .test();</span>

<span class="fc" id="L133">        pp.onError(new TestException());</span>

<span class="fc" id="L135">        to.assertFailure(TestException.class);</span>
<span class="fc" id="L136">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L140">        TestHelper.checkDisposed(Completable.merge(Flowable.just(Completable.complete())));</span>
<span class="fc" id="L141">    }</span>

    @Test
    public void disposePropagates() {

<span class="fc" id="L146">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L148">        TestObserver&lt;Void&gt; to = Completable.merge(Flowable.just(pp.ignoreElements())).test();</span>

<span class="fc" id="L150">        assertTrue(pp.hasSubscribers());</span>

<span class="fc" id="L152">        to.cancel();</span>

<span class="fc" id="L154">        assertFalse(pp.hasSubscribers());</span>

<span class="fc" id="L156">        to.assertEmpty();</span>
<span class="fc" id="L157">    }</span>

    @Test
    public void innerComplete() {
<span class="fc" id="L161">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L163">        TestObserver&lt;Void&gt; to = Completable.merge(Flowable.just(pp.ignoreElements())).test();</span>

<span class="fc" id="L165">        pp.onComplete();</span>

<span class="fc" id="L167">        to.assertResult();</span>
<span class="fc" id="L168">    }</span>

    @Test
    public void innerError() {
<span class="fc" id="L172">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L174">        TestObserver&lt;Void&gt; to = Completable.merge(Flowable.just(pp.ignoreElements())).test();</span>

<span class="fc" id="L176">        pp.onError(new TestException());</span>

<span class="fc" id="L178">        to.assertFailure(TestException.class);</span>
<span class="fc" id="L179">    }</span>

    @Test
    public void innerErrorDelayError() {
<span class="fc" id="L183">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L185">        TestObserver&lt;Void&gt; to = Completable.mergeDelayError(Flowable.just(pp.ignoreElements())).test();</span>

<span class="fc" id="L187">        pp.onError(new TestException());</span>

<span class="fc" id="L189">        to.assertFailure(TestException.class);</span>
<span class="fc" id="L190">    }</span>

    @Test
    public void mainErrorInnerErrorRace() {
<span class="fc bfc" id="L194" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L195">            List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
            try {
<span class="fc" id="L197">                final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L198">                final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L200">                TestObserver&lt;Void&gt; to = Completable.merge(pp1.map(new Function&lt;Integer, Completable&gt;() {</span>
                    @Override
                    public Completable apply(Integer v) throws Exception {
<span class="fc" id="L203">                        return pp2.ignoreElements();</span>
                    }
<span class="fc" id="L205">                })).test();</span>

<span class="fc" id="L207">                pp1.onNext(1);</span>

<span class="fc" id="L209">                final Throwable ex1 = new TestException();</span>
<span class="fc" id="L210">                final Throwable ex2 = new TestException();</span>

<span class="fc" id="L212">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L215">                        pp1.onError(ex1);</span>
<span class="fc" id="L216">                    }</span>
                };
<span class="fc" id="L218">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L221">                        pp2.onError(ex2);</span>
<span class="fc" id="L222">                    }</span>
                };

<span class="fc" id="L225">                TestHelper.race(r1, r2);</span>

<span class="fc" id="L227">                Throwable ex = to.errors().get(0);</span>
<span class="fc bfc" id="L228" title="All 2 branches covered.">                if (ex instanceof CompositeException) {</span>
<span class="fc" id="L229">                    to.assertSubscribed().assertNoValues().assertNotComplete();</span>

<span class="fc" id="L231">                    errors = TestHelper.compositeList(ex);</span>
<span class="fc" id="L232">                    TestHelper.assertError(errors, 0, TestException.class);</span>
<span class="fc" id="L233">                    TestHelper.assertError(errors, 1, TestException.class);</span>
                } else {
<span class="fc" id="L235">                    to.assertFailure(TestException.class);</span>

<span class="fc bfc" id="L237" title="All 2 branches covered.">                    if (!errors.isEmpty()) {</span>
<span class="fc" id="L238">                        TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
                    }
                }
            } finally {
<span class="fc" id="L242">                RxJavaPlugins.reset();</span>
            }
        }
<span class="fc" id="L245">    }</span>

    @Test
    public void mainErrorInnerErrorDelayedRace() {
<span class="fc bfc" id="L249" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L250">            final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L251">            final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L253">            TestObserver&lt;Void&gt; to = Completable.mergeDelayError(pp1.map(new Function&lt;Integer, Completable&gt;() {</span>
                @Override
                public Completable apply(Integer v) throws Exception {
<span class="fc" id="L256">                    return pp2.ignoreElements();</span>
                }
<span class="fc" id="L258">            })).test();</span>

<span class="fc" id="L260">            pp1.onNext(1);</span>

<span class="fc" id="L262">            final Throwable ex1 = new TestException();</span>

<span class="fc" id="L264">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L267">                    pp1.onError(ex1);</span>
<span class="fc" id="L268">                }</span>
            };

<span class="fc" id="L271">            final Throwable ex2 = new TestException();</span>
<span class="fc" id="L272">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L275">                    pp2.onError(ex2);</span>
<span class="fc" id="L276">                }</span>
            };

<span class="fc" id="L279">            TestHelper.race(r1, r2);</span>

<span class="fc" id="L281">            to.assertFailure(CompositeException.class);</span>

<span class="fc" id="L283">            List&lt;Throwable&gt; errors = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L285">            TestHelper.assertError(errors, 0, TestException.class);</span>
<span class="fc" id="L286">            TestHelper.assertError(errors, 1, TestException.class);</span>
        }
<span class="fc" id="L288">    }</span>

    @Test
    public void maxConcurrencyOne() {
<span class="fc" id="L292">        final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L293">        final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L295">        TestObserver&lt;Void&gt; to = Completable.merge(Flowable.just(pp1.ignoreElements(), pp2.ignoreElements()), 1)</span>
<span class="fc" id="L296">        .test();</span>

<span class="fc" id="L298">        assertTrue(pp1.hasSubscribers());</span>
<span class="fc" id="L299">        assertFalse(pp2.hasSubscribers());</span>

<span class="fc" id="L301">        pp1.onComplete();</span>

<span class="fc" id="L303">        assertTrue(pp2.hasSubscribers());</span>

<span class="fc" id="L305">        pp2.onComplete();</span>

<span class="fc" id="L307">        to.assertResult();</span>
<span class="fc" id="L308">    }</span>

    @Test
    public void maxConcurrencyOneDelayError() {
<span class="fc" id="L312">        final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L313">        final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L315">        TestObserver&lt;Void&gt; to = Completable.mergeDelayError(Flowable.just(pp1.ignoreElements(), pp2.ignoreElements()), 1)</span>
<span class="fc" id="L316">        .test();</span>

<span class="fc" id="L318">        assertTrue(pp1.hasSubscribers());</span>
<span class="fc" id="L319">        assertFalse(pp2.hasSubscribers());</span>

<span class="fc" id="L321">        pp1.onComplete();</span>

<span class="fc" id="L323">        assertTrue(pp2.hasSubscribers());</span>

<span class="fc" id="L325">        pp2.onComplete();</span>

<span class="fc" id="L327">        to.assertResult();</span>
<span class="fc" id="L328">    }</span>

    @Test
    public void maxConcurrencyOneDelayErrorFirst() {
<span class="fc" id="L332">        final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L333">        final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L335">        TestObserver&lt;Void&gt; to = Completable.mergeDelayError(Flowable.just(pp1.ignoreElements(), pp2.ignoreElements()), 1)</span>
<span class="fc" id="L336">        .test();</span>

<span class="fc" id="L338">        assertTrue(pp1.hasSubscribers());</span>
<span class="fc" id="L339">        assertFalse(pp2.hasSubscribers());</span>

<span class="fc" id="L341">        pp1.onError(new TestException());</span>

<span class="fc" id="L343">        assertTrue(pp2.hasSubscribers());</span>

<span class="fc" id="L345">        pp2.onComplete();</span>

<span class="fc" id="L347">        to.assertFailure(TestException.class);</span>
<span class="fc" id="L348">    }</span>

    @Test
    public void maxConcurrencyOneDelayMainErrors() {
<span class="fc" id="L352">        final PublishProcessor&lt;PublishProcessor&lt;Integer&gt;&gt; pp0 = PublishProcessor.create();</span>
<span class="fc" id="L353">        final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L354">        final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L356">        TestObserver&lt;Void&gt; to = Completable.mergeDelayError(</span>
<span class="fc" id="L357">        pp0.map(new Function&lt;PublishProcessor&lt;Integer&gt;, Completable&gt;() {</span>
            @Override
            public Completable apply(PublishProcessor&lt;Integer&gt; v) throws Exception {
<span class="fc" id="L360">                return v.ignoreElements();</span>
            }
        }), 1)
<span class="fc" id="L363">        .test();</span>

<span class="fc" id="L365">        pp0.onNext(pp1);</span>

<span class="fc" id="L367">        assertTrue(pp1.hasSubscribers());</span>
<span class="fc" id="L368">        assertFalse(pp2.hasSubscribers());</span>

<span class="fc" id="L370">        pp1.onComplete();</span>

<span class="fc" id="L372">        pp0.onNext(pp2);</span>
<span class="fc" id="L373">        pp0.onError(new TestException());</span>

<span class="fc" id="L375">        assertTrue(pp2.hasSubscribers());</span>

<span class="fc" id="L377">        pp2.onComplete();</span>

<span class="fc" id="L379">        to.assertFailure(TestException.class);</span>
<span class="fc" id="L380">    }</span>

    @Test
    public void mainDoubleOnError() {
<span class="fc" id="L384">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L386">            Completable.mergeDelayError(new Flowable&lt;Completable&gt;() {</span>
                @Override
                protected void subscribeActual(Subscriber&lt;? super Completable&gt; s) {
<span class="fc" id="L389">                    s.onSubscribe(new BooleanSubscription());</span>
<span class="fc" id="L390">                    s.onNext(Completable.complete());</span>
<span class="fc" id="L391">                    s.onError(new TestException(&quot;First&quot;));</span>
<span class="fc" id="L392">                    s.onError(new TestException(&quot;Second&quot;));</span>
<span class="fc" id="L393">                }</span>
            })
<span class="fc" id="L395">            .test()</span>
<span class="fc" id="L396">            .assertFailureAndMessage(TestException.class, &quot;First&quot;);</span>

<span class="fc" id="L398">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Second&quot;);</span>
        } finally {
<span class="fc" id="L400">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L402">    }</span>

    @Test
    public void innerDoubleOnError() {
<span class="fc" id="L406">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L408">            final CompletableObserver[] o = { null };</span>
<span class="fc" id="L409">            Completable.mergeDelayError(Flowable.just(new Completable() {</span>
                @Override
                protected void subscribeActual(CompletableObserver observer) {
<span class="fc" id="L412">                    observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L413">                    observer.onError(new TestException(&quot;First&quot;));</span>
<span class="fc" id="L414">                    o[0] = observer;</span>
<span class="fc" id="L415">                }</span>
            }))
<span class="fc" id="L417">            .test()</span>
<span class="fc" id="L418">            .assertFailureAndMessage(TestException.class, &quot;First&quot;);</span>

<span class="fc" id="L420">            o[0].onError(new TestException(&quot;Second&quot;));</span>

<span class="fc" id="L422">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Second&quot;);</span>
        } finally {
<span class="fc" id="L424">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L426">    }</span>

    @Test
    public void innerIsDisposed() {
<span class="fc" id="L430">        final TestObserver&lt;Void&gt; to = new TestObserver&lt;Void&gt;();</span>

<span class="fc" id="L432">        Completable.mergeDelayError(Flowable.just(new Completable() {</span>
            @Override
            protected void subscribeActual(CompletableObserver observer) {
<span class="fc" id="L435">                observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L436">                assertFalse(((Disposable)observer).isDisposed());</span>

<span class="fc" id="L438">                to.dispose();</span>

<span class="fc" id="L440">                assertTrue(((Disposable)observer).isDisposed());</span>
<span class="fc" id="L441">            }</span>
        }))
<span class="fc" id="L443">        .subscribe(to);</span>
<span class="fc" id="L444">    }</span>

    @Test
    public void mergeArrayInnerErrorRace() {
<span class="fc bfc" id="L448" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L449">            List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
            try {
<span class="fc" id="L451">                final PublishProcessor&lt;Integer&gt; pp1 = PublishProcessor.create();</span>
<span class="fc" id="L452">                final PublishProcessor&lt;Integer&gt; pp2 = PublishProcessor.create();</span>

<span class="fc" id="L454">                TestObserver&lt;Void&gt; to = Completable.mergeArray(pp1.ignoreElements(), pp2.ignoreElements()).test();</span>

<span class="fc" id="L456">                pp1.onNext(1);</span>

<span class="fc" id="L458">                final Throwable ex1 = new TestException();</span>
<span class="fc" id="L459">                final Throwable ex2 = new TestException();</span>

<span class="fc" id="L461">                Runnable r1 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L464">                        pp1.onError(ex1);</span>
<span class="fc" id="L465">                    }</span>
                };
<span class="fc" id="L467">                Runnable r2 = new Runnable() {</span>
                    @Override
                    public void run() {
<span class="fc" id="L470">                        pp2.onError(ex2);</span>
<span class="fc" id="L471">                    }</span>
                };

<span class="fc" id="L474">                TestHelper.race(r1, r2);</span>

<span class="fc" id="L476">                to.assertFailure(TestException.class);</span>

<span class="fc bfc" id="L478" title="All 2 branches covered.">                if (!errors.isEmpty()) {</span>
<span class="fc" id="L479">                    TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
                }
            } finally {
<span class="fc" id="L482">                RxJavaPlugins.reset();</span>
            }
        }
<span class="fc" id="L485">    }</span>

    @Test
    public void delayErrorIterableCancel() {
<span class="fc" id="L489">        Completable.mergeDelayError(Arrays.asList(Completable.complete()))</span>
<span class="fc" id="L490">        .test(true)</span>
<span class="fc" id="L491">        .assertEmpty();</span>
<span class="fc" id="L492">    }</span>

    @Test
    public void delayErrorIterableCancelAfterHasNext() {
<span class="fc" id="L496">        final TestObserver&lt;Void&gt; to = new TestObserver&lt;Void&gt;();</span>

<span class="fc" id="L498">        Completable.mergeDelayError(new Iterable&lt;Completable&gt;() {</span>
            @Override
            public Iterator&lt;Completable&gt; iterator() {
<span class="fc" id="L501">                return new Iterator&lt;Completable&gt;() {</span>
                    @Override
                    public boolean hasNext() {
<span class="fc" id="L504">                        to.cancel();</span>
<span class="fc" id="L505">                        return true;</span>
                    }

                    @Override
                    public Completable next() {
<span class="nc" id="L510">                        return Completable.complete();</span>
                    }

                    @Override
                    public void remove() {
<span class="nc" id="L515">                        throw new UnsupportedOperationException();</span>
                    }
                };
            }
        })
<span class="fc" id="L520">        .subscribe(to);</span>

<span class="fc" id="L522">        to.assertEmpty();</span>
<span class="fc" id="L523">    }</span>

    @Test
    public void delayErrorIterableCancelAfterNext() {
<span class="fc" id="L527">        final TestObserver&lt;Void&gt; to = new TestObserver&lt;Void&gt;();</span>

<span class="fc" id="L529">        Completable.mergeDelayError(new Iterable&lt;Completable&gt;() {</span>
            @Override
            public Iterator&lt;Completable&gt; iterator() {
<span class="fc" id="L532">                return new Iterator&lt;Completable&gt;() {</span>
                    @Override
                    public boolean hasNext() {
<span class="fc" id="L535">                        return true;</span>
                    }

                    @Override
                    public Completable next() {
<span class="fc" id="L540">                        to.cancel();</span>
<span class="fc" id="L541">                        return Completable.complete();</span>
                    }

                    @Override
                    public void remove() {
<span class="nc" id="L546">                        throw new UnsupportedOperationException();</span>
                    }
                };
            }
        })
<span class="fc" id="L551">        .subscribe(to);</span>

<span class="fc" id="L553">        to.assertEmpty();</span>
<span class="fc" id="L554">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>