<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>CompletableCreateTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.completable</a> &gt; <span class="el_source">CompletableCreateTest.java</span></div><h1>CompletableCreateTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.completable;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.List;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Cancellable;
import io.reactivex.plugins.RxJavaPlugins;

<span class="fc" id="L29">public class CompletableCreateTest {</span>

    @Test(expected = NullPointerException.class)
    public void nullArgument() {
<span class="nc" id="L33">        Completable.create(null);</span>
<span class="nc" id="L34">    }</span>

    @Test
    public void basic() {
<span class="fc" id="L38">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L40">            final Disposable d = Disposables.empty();</span>

<span class="fc" id="L42">            Completable.create(new CompletableOnSubscribe() {</span>
                @Override
                public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L45">                    e.setDisposable(d);</span>

<span class="fc" id="L47">                    e.onComplete();</span>
<span class="fc" id="L48">                    e.onError(new TestException());</span>
<span class="fc" id="L49">                    e.onComplete();</span>
<span class="fc" id="L50">                }</span>
            })
<span class="fc" id="L52">            .test()</span>
<span class="fc" id="L53">            .assertResult();</span>

<span class="fc" id="L55">            assertTrue(d.isDisposed());</span>

<span class="fc" id="L57">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L59">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L61">    }</span>

    @Test
    public void basicWithCancellable() {
<span class="fc" id="L65">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L67">            final Disposable d1 = Disposables.empty();</span>
<span class="fc" id="L68">            final Disposable d2 = Disposables.empty();</span>

<span class="fc" id="L70">            Completable.create(new CompletableOnSubscribe() {</span>
                @Override
                public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L73">                    e.setDisposable(d1);</span>
<span class="fc" id="L74">                    e.setCancellable(new Cancellable() {</span>
                        @Override
                        public void cancel() throws Exception {
<span class="fc" id="L77">                            d2.dispose();</span>
<span class="fc" id="L78">                        }</span>
                    });

<span class="fc" id="L81">                    e.onComplete();</span>
<span class="fc" id="L82">                    e.onError(new TestException());</span>
<span class="fc" id="L83">                    e.onComplete();</span>
<span class="fc" id="L84">                }</span>
            })
<span class="fc" id="L86">            .test()</span>
<span class="fc" id="L87">            .assertResult();</span>

<span class="fc" id="L89">            assertTrue(d1.isDisposed());</span>
<span class="fc" id="L90">            assertTrue(d2.isDisposed());</span>

<span class="fc" id="L92">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L94">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L96">    }</span>

    @Test
    public void basicWithError() {
<span class="fc" id="L100">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L102">            final Disposable d = Disposables.empty();</span>

<span class="fc" id="L104">            Completable.create(new CompletableOnSubscribe() {</span>
                @Override
                public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L107">                    e.setDisposable(d);</span>

<span class="fc" id="L109">                    e.onError(new TestException());</span>
<span class="fc" id="L110">                    e.onComplete();</span>
<span class="fc" id="L111">                    e.onError(new TestException(&quot;second&quot;));</span>
<span class="fc" id="L112">                }</span>
            })
<span class="fc" id="L114">            .test()</span>
<span class="fc" id="L115">            .assertFailure(TestException.class);</span>

<span class="fc" id="L117">            assertTrue(d.isDisposed());</span>

<span class="fc" id="L119">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;second&quot;);</span>
        } finally {
<span class="fc" id="L121">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L123">    }</span>

    @Test
    public void callbackThrows() {
<span class="fc" id="L127">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L130">                throw new TestException();</span>
            }
        })
<span class="fc" id="L133">        .test()</span>
<span class="fc" id="L134">        .assertFailure(TestException.class);</span>
<span class="fc" id="L135">    }</span>

    @Test
    public void onErrorNull() {
<span class="fc" id="L139">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L142">                e.onError(null);</span>
<span class="fc" id="L143">            }</span>
        })
<span class="fc" id="L145">        .test()</span>
<span class="fc" id="L146">        .assertFailure(NullPointerException.class);</span>
<span class="fc" id="L147">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L151">        TestHelper.checkDisposed(Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L154">                e.onComplete();</span>
<span class="fc" id="L155">            }</span>
        }));
<span class="fc" id="L157">    }</span>

    @Test
    public void onErrorThrows() {
<span class="fc" id="L161">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L164">                Disposable d = Disposables.empty();</span>
<span class="fc" id="L165">                e.setDisposable(d);</span>

                try {
<span class="nc" id="L168">                    e.onError(new IOException());</span>
<span class="nc" id="L169">                    fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L170">                } catch (TestException ex) {</span>
                    // expected
<span class="nc" id="L172">                }</span>

<span class="fc" id="L174">                assertTrue(d.isDisposed());</span>
<span class="fc" id="L175">                assertTrue(e.isDisposed());</span>
<span class="fc" id="L176">            }</span>
<span class="fc" id="L177">        }).subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L182">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L186">                throw new TestException();</span>
            }

            @Override
            public void onComplete() {

<span class="nc" id="L192">            }</span>
        });
<span class="fc" id="L194">    }</span>

    @Test
    public void onCompleteThrows() {
<span class="fc" id="L198">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L201">                Disposable d = Disposables.empty();</span>
<span class="fc" id="L202">                e.setDisposable(d);</span>

                try {
<span class="nc" id="L205">                    e.onComplete();</span>
<span class="nc" id="L206">                    fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L207">                } catch (TestException ex) {</span>
                    // expected
<span class="nc" id="L209">                }</span>

<span class="fc" id="L211">                assertTrue(d.isDisposed());</span>
<span class="fc" id="L212">                assertTrue(e.isDisposed());</span>
<span class="fc" id="L213">            }</span>
<span class="fc" id="L214">        }).subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L219">            }</span>

            @Override
            public void onError(Throwable e) {

<span class="nc" id="L224">            }</span>

            @Override
            public void onComplete() {
<span class="fc" id="L228">                throw new TestException();</span>
            }
        });
<span class="fc" id="L231">    }</span>

    @Test
    public void onErrorThrows2() {
<span class="fc" id="L235">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
                try {
<span class="nc" id="L239">                    e.onError(new IOException());</span>
<span class="nc" id="L240">                    fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L241">                } catch (TestException ex) {</span>
                    // expected
<span class="nc" id="L243">                }</span>

<span class="fc" id="L245">                assertTrue(e.isDisposed());</span>
<span class="fc" id="L246">            }</span>
<span class="fc" id="L247">        }).subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L252">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L256">                throw new TestException();</span>
            }

            @Override
            public void onComplete() {

<span class="nc" id="L262">            }</span>
        });
<span class="fc" id="L264">    }</span>

    @Test
    public void onCompleteThrows2() {
<span class="fc" id="L268">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter e) throws Exception {
                try {
<span class="nc" id="L272">                    e.onComplete();</span>
<span class="nc" id="L273">                    fail(&quot;Should have thrown&quot;);</span>
<span class="fc" id="L274">                } catch (TestException ex) {</span>
                    // expected
<span class="nc" id="L276">                }</span>

<span class="fc" id="L278">                assertTrue(e.isDisposed());</span>
<span class="fc" id="L279">            }</span>
<span class="fc" id="L280">        }).subscribe(new CompletableObserver() {</span>

            @Override
            public void onSubscribe(Disposable d) {

<span class="fc" id="L285">            }</span>

            @Override
            public void onError(Throwable e) {

<span class="nc" id="L290">            }</span>

            @Override
            public void onComplete() {
<span class="fc" id="L294">                throw new TestException();</span>
            }
        });
<span class="fc" id="L297">    }</span>

    @Test
    public void tryOnError() {
<span class="fc" id="L301">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L303">            final Boolean[] response = { null };</span>
<span class="fc" id="L304">            Completable.create(new CompletableOnSubscribe() {</span>
                @Override
                public void subscribe(CompletableEmitter e) throws Exception {
<span class="fc" id="L307">                    e.onComplete();</span>
<span class="fc" id="L308">                    response[0] = e.tryOnError(new TestException());</span>
<span class="fc" id="L309">                }</span>
            })
<span class="fc" id="L311">            .test()</span>
<span class="fc" id="L312">            .assertResult();</span>

<span class="fc" id="L314">            assertFalse(response[0]);</span>

<span class="fc" id="L316">            assertTrue(errors.toString(), errors.isEmpty());</span>
        } finally {
<span class="fc" id="L318">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L320">    }</span>

    @Test
    public void emitterHasToString() {
<span class="fc" id="L324">        Completable.create(new CompletableOnSubscribe() {</span>
            @Override
            public void subscribe(CompletableEmitter emitter) throws Exception {
<span class="fc" id="L327">                assertTrue(emitter.toString().contains(CompletableCreate.Emitter.class.getSimpleName()));</span>
<span class="fc" id="L328">            }</span>
<span class="fc" id="L329">        }).test().assertEmpty();</span>
<span class="fc" id="L330">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>